.TH urpmi.removemedia 8 "2001eko uztailak 05" "Mandrakesoft" "Mandrakelinux"
.IX urpmi.removemedia
.SH IZENA
urpmi.removemedia \- urpmi-ren euskarri ezagunetatik rpm euskarriak kentzen ditu
.SH LABURPENA
.B urpmi.removemedia [aukerak] <\fIizenak\fP>
.SH AZALPENA
urpmi.removemedia aipatutako euskarriaren eta euskarri horren rpm guztien
erreferentzia guztiak kentzen ditu konfigurazio-fitxategi guzietatik.
.PP
<\fIizenak\fP> lehenagotik urpmi.addmedia-ri eman dizkiozun izenen zerrenda da

.SH AUKERAK
.IP "\fB\-a\fP"
Euskarri guztiak hautatzen ditu, ezabatzeko.
.SH FITXATEGIAK
/usr/bin/urpmi
.br
\fBurpmi\fP exekutagarria (perl script-a)
.PP
/var/lib/urpmi/list.*
.br
urpmi-k ezagututako pakete guztien zerrenda eta haien kokalekua du.
Fitxategi-zerrenda bat dago euskarri bakoitzeko(*).
.PP
/var/lib/urpmi/hdlist.*
.br
Pakete ezagun guztiei buruzko informazioa du; rpm goiburukoen laburpena da.
Fitxategi-zerrenda bat dago euskarri bakoitzeko(*).
.PP
/etc/urpmi/urpmi.cfg
.br
urpmi zaharragoaren formatua onartu aurretik, euskarriaren azalpena du.
.PP
/etc/urpmi/skip.list
.br
Automatikoki eguneratu behar ez diren paketeen izenak ditu.
.PP
/var/lib/urpmi/depslist.ordered
.br
Pakete ezagun guztien mendekotasun guztiak dituen testu-fitxategi soila.
.PP
/var/lib/urpmi/provides
.br
Hornigai guztiak eta hornigaiok dituzten paketeen zerrenda dituen
testu-fitxategi soila.
.PP
/var/lib/urpmi/compss
.br
Erabilitako talde bakoitzeko, talde horretako pakete-zerrenda duen 
testu-fitxategi soila.
.SH "IKUSI BAITA ERE"
urpmi(8),
urpmi.addmedia(8),
autoirpm(8),
autoirpm-icons(8),
urpmf(8),
urpmq(8),
.SH EGILEA
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com>
.br
Francois Pons, Mandrakesoft <fpons@mandrakesoft.com>
.br
Rafael Garcia-Suarez, Mandrakesoft <rgarciasuarez@mandrakesoft.com>

