=head1 NAME

urpmi.recover - manages repackaging of old RPMs and rollbacks

=head1 SYNOPSIS

    urpmi.recover --checkpoint
    urpmi.recover --list '1 week ago'
    urpmi.recover --rollback '1 hour ago'

=head1 DESCRIPTION

=head1 OPTIONS

=over 4

=item --checkpoint

=item --noclean

=item --list

=item --list-all

=item --rollback

=back

=head1 AUTHOR

Rafael Garcia-Suarez, <rgarciasuarez@mandriva.com>

=head1 SEE ALSO

urpmi(8), urpme(8)
