.TH autoirpm 8 "05 Sep 2000" "Mandrakesoft" "Linux-Mandrake"
.IX autoirpm
.SH NAME
autoirpm \- installe automatiquement le RPM correspondant à votre commande
.SH SYNOPSIS
.B autoirpm
.SH DESCRIPTION
autoirpm devine *magiquement* le paquetage dont vous avez besoin et l'installe.
Imaginez que vous tapiez gmix pour lancer votre table de mixage audio. S'il
n'est pas disponible, on vous demandera si vous souhaitez installer le
paquetage gnome-media qui contient le binaire gmix...
.PP
Pour cela, lancez autoirpm.update-all, qui scanne tous les paquetages connus
par urpmi à la recherche de tous les exécutables binaires. Il crée ensuite
des liens dans les répertoires respectifs de ces exécutables...
Utilisez autoirpm.uninstall pour retirer tous les liens créés par autoirpm.update.
.PP
utilisez \fBautoirpm.update <nom>\fP pour mettre à jour les exécutables contenus
dans les paquetages du média <nom>mé.
.PP
utilisez \fBautoirpm.update-all\fP pour mettre à jour les exécutables contenus
dans tous les médias connus par urpmi.
.PP
utilisez \fBautoirpm.uninstall\fP pour retirer tous les liens installés par autoirpm.
.PP
This feature may be offered for menu icons installing autoirpm-icons package.
.SH FICHIERS
/etc/urpmi/autoirpm.deny
.br
Tous les binaires contenus dans les paquetages listés dans ce fichier ne mèneront pas
à une installation automatique du rpm.
.PP
/etc/urpmi/autoirpm.allow
.br
Si présent, seuls les binaires des paquetages listés offriront la fonction auto-install. 

.SH "VOIR AUSSI"
urpmi(8)
.SH AUTEUR
Pascal Rigaux, Mandrakesoft
.br
pixel@mandrakesoft.com









