.TH urpmi 8 "4 Jun 2002" "MandrakeSoft" "Mandrake Linux"
.IX urpmi
.SH NOM
urpmi \- interface rpm pour simplifier les installations
.SH SYNOPSIS
.B urpmi [\fIoptions\fP] [\fIpackage_names\fP | \fIrpm_files...\fP]
.SH DESCRIPTION
urpmi autorise les rpms bien connus (ou les fichier .rpm) à être installés ainsi
que leurs dépendances.
Vous pouvez l'utiliser pour installer les dépendances d'un paquetage source en
tant que super-utilisateur (root) ou le paquetage source lui même en tant que
simple utilisateur.

En fait, rpm est à urpmi ce que insmod est à modprobe, ou dpkg à apt-get.
.PP
Lancez urpmi suivi de ce que vous pensez être le nom du/des paquetages(s),
et urpmi :
.br
\- Proposera des noms de paquetages possibles s'ils existent, et quittera.
.br
\- Vérifiera si les dépendances sont déjà installées, dans le cas où un seul
paquetage est trouvé.
.br
\- Proposera d'installer les dépendances si elles sont absentes, installera
toutes les dépendances nécessaires après acceptation, puis le paquetage voulu.
.PP
Veuillez noter que urpmi gère les installations à partir de divers médias (ftp,
http, volumes nfs et locaux, médias amovibles commes les cédéroms), et peut
installer les dépendances à partir d'un média différent du médium du paquetage.
Si nécessaire, urpmi vous demandera d'insérer le médium nécessaire.
.PP
Pour ajouter un nouveau médium contenant des rpms, lancez urpmi.addmedia.
.br
Pour retirer un médium, utilisez urpmi.removemedia.
.br
Pour mettre à jour la liste des paquetages, (par exemple quand l'archive ftp
a changé) utilisez urpmi.update.
.br
Pour installer automatiquement un paquetage correspondant à un exécutable que
vous avez tenté de lancer, utilisez autoirpm.
.br
Pour installer toutes les entrées de menu de tous les paquetages connus, utilisez
autoirpm-icons.
.SH OPTIONS
.IP "\fB\--help\fP"
affiche un message d'aide et quitte (identique à \fB-h\fP ou \fB-?\fP).
.IP "\fB\--update\fP"
utilise seulement des médias de mise à jour. Cela signifie que \fBurpmi\fP
ne recherchera et ne résoudra les dépendances que sur les médias marqués comme
mises à jour.
.IP "\fB\--media\fP"
sélectionne les media donnée plutôt que tous les media disponibles.
.IP "\fB\--auto\fP"
installe toutes les dépendances nécessaires sans rien demander.
.IP "\fB\--auto-select\fP"
sélectionne automatiquement tous les paquetages qui doivent être mis à jour
selon les paquetages déjà installés et les paquetages listés dans les divers
médias enregistrés.
.IP "\fB\--fuzzy\fP"
désactive la recherche rapide sur un nom de paquetage exact et propose tous les
noms de paquetage correspondant au paramètre donnée (identique à \fB-y\fP).
.IP "\fB\--src\fP"
le prochain nom de paquetage est considéré comme étant un nom de paquetage
source.
.IP "\fB\--noclean\fP"
ne suprime aucun paquetages du cache (/var/cache/urpmi/rpms).
.IP "\fB\--complete\fP"
utilise le serveur parsehdlist pour étendre la recherche de paquetages à mettre
à jour au moyen de \fB--auto-select\fP (ne doit pas être nécessaire dans la
majorité des cas).
.IP "\fB\--force\fP"
répond par l'affirmative à toutes les questions.
.IP "\fB\--wget\fP"
utilise wget pour télécharger les fichiers. Par défaut curl est utilisé s'il est
disponible ou wget dans le cas contraire.
.IP "\fB\--curl\fP"
utilise curl pour télécharger les fichiers. Par défaut curl est utilisé s'il est
disponible ou wget dans le cas contraire.
.IP "\fB\--X\fP"
utilise l'interface X.
.IP "\fB\--best-output\fP"
essaye d'utiliser l'interface X, ou si elle n'est pas disponible, l'interface
en mode texte (qui utilise rpm).
.IP "\fB\-a\fP"
si plusieurs paquetages coïncident avec la sous-chaîne donnée, les prendre tous.
.IP "\fB\-p\fP"
autorise la recherche dans "provides" pour trouver un paquetage (par défaut).
.IP "\fB\-P\fP"
désactive la recherche dans "provides" pour trouver un paquetage.
.IP "\fB\-y\fP"
identique à \fB--fuzzy\fP.
.IP "\fB\-s\fP"
identique à \fB--src\fP.
.IP "\fB\-q\fP"
active le mode silencieux pour la mise à jour utilisant rpm 
.IP "\fB\-v\fP"
active un mode verbeux avec de nombreux messages.
.SH FICHIERS
/usr/sbin/urpmi
.br
L'exécutable \fBurpmi\fP (script perl)
.PP
/var/lib/urpmi/list.*
.br
Contient la liste de tous les paquetages connus par urpmi et leur emplacement.
Il y a une liste de fichiers par médium(*).
.PP
/var/lib/urpmi/hdlist.*
.br
Contient l'information sur tous les paquetages connus, c'est un résumé des
entêtes de rpm.
Il y a un fichier hdlist par médium(*).
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Contient une synthèse de tous les paquetages connus construits à partir des
fichiers hdlist qui peut être utilisée pour l'algorithme de l'ensemble minimal.
Si ces fichiers ne sont pas présents, utilisez \fBurpmi.update -a\fP pour les
générer. Ces fichiers ne sont pas obligatoires.
.PP
/etc/urpmi/urpmi.cfg
.br
Contient la description du médium, l'ancien format urpmi est accepté.
.PP
/etc/urpmi/skip.list
.br
Contient les noms de paquetages à ne pas mettre à jour automatiquement.
.PP
/etc/urpmi/inst.list
.br
Contient les noms de paquetages à installer plutôt qu'à mettre à jour.
.SH "VOIR AUSSI"
urpmi.addmedia(8),
urpmi.update(8),
urpmi.removemedia(8),
autoirpm(8),
gurpmi(8),
urpmf(8),
urpmq(8),
rpmdrake(8)
.SH AUTEURS
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com>
.br
Francois Pons, Mandrakesoft <fpons@mandrakesoft.com>
