/* this is a placeholder so that xgettext can find the translatable
 * strings. This file is automatically generated, look at
 * po/create_placeholder
 */
char *foobar[] = { 
N_("usage: rpmf [<file>]"),
N_("urpmi is not installed"),
N_(""
"urpmi version %s\n"
"Copyright (C) 1999, 2000, 2001 MandrakeSoft.\n"
"This is free software and may be redistributed under the terms of the GNU GPL.\n"
"usage:\n"
"  --help           - print this help message.\n"
"  --auto           - automatically select a good package in choices.\n"
"  --auto-select    - automatically select packages for upgrading the system.\n"
"  --force          - force invocation even if some package do not exist.\n"
"  --X              - use X interface.\n"
"  --best-output    - choose best interface according to the environment:\n"
"                     X or text mode.\n"
"  -a               - select all matches on command line.\n"
"  -m               - choose minimum closure of requires (default).\n"
"  -M               - choose maximun closure of requires.\n"
"  -c               - choose complete method for resolving requires closure.\n"
"  -q               - quiet mode.\n"
"  -v               - verbose mode.\n"
"  names or rpm files (only for root) given on command line are installed.\n"
""),
N_(""
"usage: urpmi.addmedia <name> <url>\n"
"where <url> is one of\n"
"       file://<path>\n"
"       ftp://<login>:<password>@<host>/<path> with <relative filename of hdlist>\n"
"       ftp://<host>/<path> with <relative filename of hdlist>\n"
"       http://<host>/<path> with <relative filename of hdlist>\n"
"       removable_<device>://<path>\n"
""),
N_(""
"%s\n"
"`with' missing for ftp media\n"
""),
N_(""
"%s\n"
"device `%s' do not exist\n"
""),
N_(""
"%s\n"
"<relative path of hdlist> missing\n"
""),
N_(""
"the entry to update is missing\n"
"(one of %s)\n"
""),
N_(""
"usage: urpmi.update [-a] <name> ...\n"
"where <name> is a medium name to update.\n"
"   -a    select all non-removable media.\n"
"\n"
"unknown options '%s'\n"
""),
N_(""
"usage: urpmi.removemedia [-a] <name> ...\n"
"where <name> is a medium name to remove.\n"
"   -a    select all media.\n"
"\n"
"unknown options '%s'\n"
""),
N_(""
"the entry to remove is missing\n"
"(one of %s)\n"
""),
};
