.TH urpmi.removemedia 8 "10 Apr 2001" "Mandrakesoft" "Linux-Mandrake"
.IX urpmi.removemedia
.SH NAME
urpmi.removemedia \- remove a rpms media from the known medias of urpmi
.SH SYNOPSIS
.B urpmi.removemedia [options] <\fInames\fP>
.SH DESCRIPTION
urpmi.removemedia removes from all configuration files all references to
the named media and to rpms from that media.
.PP
<\fInames\fP> is a list of names you first told to urpmi.addmedia

.SH OPTION
.IP "\fB\-a\fP"
Select all media to remove them.
.SH FILES
/usr/bin/urpmi
.br
The \fBurpmi\fP executable (perl script)
.PP
/var/lib/urpmi/list.*
.br
Contains the list of all packages known by urpmi and their location.
There is one filelist per media(*).
.PP
/var/lib/urpmi/hdlist.*
.br
Contain information about all known packages, it's a summary of rpm headers.
There is one filelist per media(*).
.PP
/etc/urpmi/urpmi.cfg
.br
Contains media description, previous format from older urpmi is accepted.
.PP
/etc/urpmi/skip.list
.br
Contains package names that should be not automatically updated.
.PP
/var/lib/urpmi/depslist.ordered
.br
A simple text file containing all dependencies of all known packages.
.PP
/var/lib/urpmi/provides
.br
A simple text file containning all provides and the list of associated
packages that contains them.
.PP
/var/lib/urpmi/compss
.br
A simple text file containning for each Group used the list of package in
this group.
.SH "SEE ALSO"
urpmi(8),
urpmi.addmedia(8),
autoirpm(8),
autoirpm-icons(8),
gurpmi(8),
urpmf(8),
urpmq(8),
rpmdrake(8)
.SH AUTHOR
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com>
.br
Francois Pons, Mandrakesoft <fpons@mandrakesoft.com>
