#!/bin/sh

unalias ls 2>/dev/null

if [ "$#" -gt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "usage: rpmf [<file>]"
    exit 1
fi

dir="/var/lib/urpmi"


if ls $dir/hdlist.*.gz >/dev/null 2>/dev/null; then
    found=1
    gzip -dc $dir/hdlist.*.gz | hdlist2files - | grep -E "$1"
fi
if ls $dir/hdlist.*.cz2 >/dev/null 2>/dev/null; then
    found=1
    bzip2 -dc $dir/hdlist.*.cz2 2>/dev/null | hdlist2files - | grep -E "$1"
fi
if [ "$found" != "1" ]; then
    echo "urpmi is not installed"
    exit 1
fi

