.TH urpmi 8 "10 Apr 2001" "Mandrakesoft" "Linux-Mandrake"
.IX urpmi
.SH NAME
urpmi \- rpm wrapper making installs easier for the user
.SH SYNOPSIS
.B urpmi [options] [package_names|rpm_files...]
.SH DESCRIPTION
urpmi enables non-superuser install of rpms. In fact, it only authorizes
well-known rpms to be installed. If you want to install local rpm file, you
will have to be root.

You can compare rpm vs. urpmi  with  insmod vs. modprobe or dpkg vs apt-get
.PP
All users belonging to group urpmi are allowed to install packages.
.br
Just launch urpmi followed by what you think is the name of the package(s),
and urpmi will:
.br
\- Propose different package names if availables and quit.
.br
\- If found only one package corresponding, check wether dependencies are
already installed or not.
.br
\- If not, propose to install the dependencies and then install all required
dependencies and the package.
.PP
Note that urpmi handle installations from various medias (ftp, http, local and
nfs volumes, removable medias such as CDROMs) and is able to install
dependencies from a media different from the package's media.
If necessary, urpmi asks you to insert the required media.
.PP
To add a new media containing rpms run urpmi.addmedia.
.br
To remove a media use urpmi.removemedia.
.br
To update the packages list (for example when the ftp archive changed) use
urpmi.update.
.br
To automatically install a package corresponding to an executable you tried
to launch, use autoirpm.
.br
To install all available menu entries of all known packages,
use autoirpm-icons.
.SH OPTION
.IP "\fB\--help\fP"
print an help message and exit.
.IP "\fB\--auto\fP"
installs all required dependencies without asking.
.IP "\fB\--auto-select\fP"
automatically select all packages that have to be upgraded according to already
installed packages and packages listed in various media registered.
.IP "\fB\--force\fP"
assumes yes on all questions.
.IP "\fB\--X\fP"
use X interface.
.IP "\fB\--best-output\fP"
try to use X interface or if not available the standard text interface (using
rpm).
.IP "\fB\-a\fP"
if multiple packages match the substring given, take them all
.IP "\fB\-m\fP"
choose minimun closure of requires (this is the default). This is a relatively
slow algorithm that tries to minimize the number of package to upgrade
to only what is really necessary.
.IP "\fB\-M\fP"
choose maximal closure of requires. This is the fastest algorithms that try to
upgrade all requires if they can be upgraded.
.IP "\fB\-c\fP"
if maximal closure is used, assume that a package listed mey have wrong or not
up-to-date dependancies. This cause more package to be upgraded and may correct
unresolved dependancies on the rpm database.
.IP "\fB\-q\fP"
proposes a quiet mode when calling rpm where no upgrade status are printed.
.IP "\fB\-v\fP"
proposes a verbose mode with various messages.
.SH FILES
/usr/bin/urpmi
.br
The \fBurpmi\fP executable (perl script)
.PP
/var/lib/urpmi/list.*
.br
Contains the list of all packages known by urpmi and their location.
There is one filelist per media(*).
.PP
/var/lib/urpmi/hdlist.*
.br
Contain information about all known packages, it's a summary of rpm headers.
There is one hdlist per media(*).
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Contain synthesis information about all known packages built from hdlist files
that can be used by minimal closure algorithm. If these files are not present
use \fBurpmi.update -a\fP to generate them. These files are not mandatory.
.PP
/etc/urpmi/urpmi.cfg
.br
Contains media description, previous format from older urpmi is accepted.
.PP
/etc/urpmi/skip.list
.br
Contains package names that should be not automatically updated.
.PP
/var/lib/urpmi/depslist.ordered
.br
A simple text file containning all dependencies of all known packages.
.PP
/var/lib/urpmi/provides
.br
A simple text file containning all provides and the list of associated
packages that contains them.
.PP
/var/lib/urpmi/compss
.br
A simple text file containning for each Group used the list of package in
this group.
.SH "SEE ALSO"
urpmi.addmedia(8),
urpmi.update(8),
urpmi.removemedia(8),
autoirpm(8),
gurpmi(8),
urpmf(8),
urpmq(8),
rpmdrake(8)
.SH AUTHOR
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com>
.br
Francois Pons, Mandrakesoft <fpons@mandrakesoft.com>
