.TH urpmi.update 8 "05 Sep 2000" "Mandrakesoft" "Linux-Mandrake"
.IX urpmi.update
.SH NAME
urpmi.update \- Updates packages list for specified medias
.SH SYNOPSIS
.B urpmi.update <\fIname\fP>
.SH DESCRIPTION
urpmi.update scans the <\fIname\fP> media to update its packages list.
Usefull for ftp location for example.
.PP
<\fIname\fP> is the name you first told to urpmi.addmedia

.SH FILES
/usr/bin/urpmi
.br
The \fBurpmi\fP executable (perl script)
.PP
/var/lib/urpmi/list.*
.br
Contains the list of all packages known by urpmi and their location.
There is one filelist per media(*).
.PP
/var/lib/urpmi/hdlist.*
.br
Contain information about all known packages, it's a summary of rpm headers.
There is one filelist per media(*).
.PP
/etc/urpmi/urpmi.cfg
.br
Contains one line <\fIname\fP> <\fIurl\fP> per media.
.PP
/var/lib/urpmi/depslist.ordered
.br
A simple text file containing all dependencies of all known packages.
.PP
/var/lib/urpmi/provides
.br
A simple text file containning all provides and the list of associated
packages that contains them.
.PP
/var/lib/urpmi/compss
.br
A simple text file containning for each Group used the list of package in
this group.
.SH "SEE ALSO"
urpmi(8),
urpmi.addmedia(8),
urpmf(8),
urpmq(8),
autoirpm(8),
autoirpm-icons(8),
gurpmi(8),
rpmdrake(8)
.SH AUTHOR
Pascal Rigaux, Mandrakesoft
.br
pixel@mandrakesoft.com









