.TH urpmf 8 "10 Apr 2001" "Mandrakesoft" "Linux-Mandrake"
.IX urpmf
.SH NAME
urpmf \- RPMFind - Finds the RPM package providing the specified file
.SH SYNOPSIS
.B urpmf [<\fIFile\fP>]
.SH DESCRIPTION
urpmf outputs a list of packages providing the file specified as an argument.
.PP
<\fIFile\fP> is the name of the file you wish to know the package providing
it. Note that you may type just a substring of the file you are looking for,
\fBrpmf\fP will then print a list of matching files with their corresponding
packages.
.PP
urpmf searches through installed and uninstalled packages.
.SH FILES
/usr/bin/urpmf
.br
The \fBurpmf\fP executable (perl script)
.PP
/var/lib/urpmi/list.*
.br
Contains the list of all packages known by urpmi and their location.
There is one filelist per media(*).
.PP
/var/lib/urpmi/hdlist.*
.br
Contain information about all known packages, it's a summary of rpm headers.
There is one filelist per media(*).
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Contain synthesis information about all known packages built from hdlist files
that can be used by minimal closure algorithm. If these files are not present
use \fBurpmi.update -a\fP to generate them. These files are not mandatory.
.PP
/etc/urpmi/urpmi.cfg
.br
Contains media description, previous format from older urpmi is accepted.
.PP
/etc/urpmi/skip.list
.br
Contains package names that should be not automatically updated.
.PP
/var/lib/urpmi/depslist.ordered
.br
A simple text file containing all dependencies of all known packages.
.PP
/var/lib/urpmi/provides
.br
A simple text file containning all provides and the list of associated
packages that contains them.
.PP
/var/lib/urpmi/compss
.br
A simple text file containning for each Group used the list of package in
this group.
.SH "SEE ALSO"
urpmi(8),
urpmq(8),
urpmi.addmedia(8),
urpmi.update(8),
urpmi.removemedia(8),
autoirpm(8),
autoirpm-icons(8),
gurpmi(8),
rpmdrake(8)
.SH AUTHOR
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com>
.br
Francois Pons, Mandrakesoft <fpons@mandrakesoft.com>
