.TH urpmi 8 "28 Srp 2003" "Mandrakesoft" "Mandrakelinux"
.IX urpmi
.SH NÁZEV
urpmi \- obaluje program rpm a usnadňuje uživateli instalace
.SH SYNAPSE
.B urpmi [\fIvolby\fP] [\fInázev_balíčku\fP | \fIsoubory_rpm...\fP]
.SH POPIS
Program urpmi povoluje instalaci balíčků RPM a balíčků na nich závislých. Lze jej použít pro instalaci balíčků se zdroji nebo balíčků na nich závislých.
.PP
Vzájemný vztah mezi programy rpm a urpmi lze srovnat se vztahem mezi programy
insmod a modprobe, nebo mezi dpkg a apt-get.
.PP
Spusťte program urpmi následovaný tím, co pokládáte za název balíčku nebo balíčků, a program urpmi:
.br
\- Nabídne názvy jiných balíčků, pokud jsou k dispozici, a ukončí se.
.br
\- Pokud je nalezen pouze jeden odpovídající balíček, zkontroluje, zda jsou již nainstalované balíčky, na kterých tento závisí.
.br
\- Pokud nejsou, nabídne instalaci závisejících balíčků, a poté nainstaluje všechny závisející balíčky i balíček samotný.
.PP
Všimněte si, že program urpmi zvládne instalaci z různých zdrojů (FTP, HTTP, lokální a NFS svazky, vyjímatelná média jako CDROM), a že je schopen instalovat závislé balíčky ze zdroje jiného než je zdroj instalovaného balíčku. Pokud je to nutné, požádá vás program urpmi o vložení požadovaného média.
.PP
Chcete-li přidat další zdroj obsahující balíčky RPM, spusťte program urpmi.addmedia.
.br
Chcete-li odstranit zdroj, použijte program urpmi.removemedia.
.br
Chcete-li aktualizovat seznam balíčků (pokud se například změnil FTP archív), použijte program urpmi.update.
.br
Chcete-li nainstalovat balíček odpovídající spustitelnému souboru, který se pokoušíte spustit, použijte program autoirpm.
.br
Chcete-li doinstalovat položky do všech známých balíčků, použijte balíček autoirpm-icons.
.SH VOLBY
.IP "\fB\--help\fP"
zobrazí nápovědu a ukončí se.
.IP "\fB\--update\fP"
použije pouze zdroje pro aktualizaci. To znamená, že program \fBurpmi\fP bude hledat a řešit závislosti pouze ve zdrojích,
které jsou označené jako zdroje pro aktualizaci.
.IP "\fB\--media\fP \fIzdroj1,...,zdrojN\fP"
použije pouze zadané zdroje, nikoli všechny dostupné zdroje (nebo zdroje pro aktualizaci, pokud je zadána volba \fB\--update\fP).
.IP "\fB\--excludemedia\fP \fIzdroj1,...,zdrojN\fP"
nepoužije zadané zdroje.
.IP "\fB\--sortmedia\fP \fIzdroj1,...,zdrojN\fP"
setřídí zadané zdroje, ke zjednodušení seskupení lze použít podřetězce.
.IP "\fB\--synthesis\fP \fIsoubor\fP"
pro vyhledávání v balíčcích a řešení závislostí použije místo databáze urpmi zadaný \fIsoubor\fP syntézy.
.IP "\fB\--auto\fP"
instaluje všechny potřebné závislosti bez dotazů.
.IP "\fB\--auto-select\fP"
automaticky vybere všechny balíčky, které musí být aktualizovány, podle již instalovaných balíčků a balíčků uvedených v různých registrovaných zdrojích.
.IP "\fB\--no-uninstall\fP"
nebude se ptát, zda-li chcete odinstalovat balíček, místo toho přeruší instalaci. Tato volba může učinit automatický režim bezpečnější.
.IP "\fB\--keep\fP"
změní výběr balíčků, pokud nemohou být uspokojeny některé závislosti tak, že se pokusí ponechat existující balíčky místo toho, aby je odstranil. Toto chování obecně odmítne aktualizaci balíčků zadaných na příkazové řádce (nebo při použití volby --auto-select), pokud dojde k chybě v závislostech.
.IP "\fB\--split-level\fP \fIčíslo\fP"
rozdělí aktualizaci na více menších transakcí, pokud počet aktualizovaných balíčků přesáhne zadané \fIčíslo\fP. Tato volba je implicitně aktivní a výchozí hodnota počtu balíčků je 20.
.IP "\fB\--split-length\fP \fIčíslo\fP"
rozdělí aktualizaci do menších transakcí, každá z nich musí obsahovat alespoň \fIčíslo\fP balíčků. Výchozí hodnota je 1, pokud zadáte hodnotu 0, pak dělení do menších transakcí vypnete.
.IP "\fB\--fuzzy\fP"
vypne rychlé hledání přesného názvu balíčku, jinými slovy navrhne všechny balíčky obsahující zadaný název, i pokud existuje takový, který má zadaný název (tato volba je stejná jako volba \fB\-y\fP.
.IP "\fB\--src\fP \fInázev\fP"
prohledává zdrojový balíček podle \fInázvu\fP a implicitně vybere všechny závislosti, pokud není zadaná volba \fB\--install-src\fP pro instalaci zdrojového balíčku samotného.
.IP "\fB\--install-src\fP"
nainstaluje pouze zdrojový balíček (nebude nainstalován žádný binární balíček).
.IP "\fB\--clean\fP"
odstraní všechny balíčky z vyrovnávací paměti v adresáři /var/cache/urpmi/rpms.
.IP "\fB\--noclean\fP"
neodstraní žádný balíček z vyrovnávací paměti v adresáři /var/cache/urpmi/rpms.
.IP "\fB\--force\fP"
předpokládá kladnou odpověď na všechny otázky.
.IP "\fB\--allow-nodeps\fP"
povolí programu urpmi zeptat se uživatele, zda se má pokračovat v instalaci bez kontroly závislostí v případě jejich porušení díky chybě. Výchozí chování je instalaci okamžitě ukončit.
.IP "\fB\--allow-force\fP"
povolí programu urpmi zeptat se uživatele, zda se má pokračovat v instalaci bez kontroly závislostí v případě jejich porušení díky chybě nebo zda se má provést instalace násilím. Výchozí chování je instalaci v takových případech okamžitě ukončit.
.IP "\fB\--parallel\fP \fIalias\fP"
aktivuje distribuované spuštění urpmi na dalších počítačích (je nutné, aby na těchto počítačích bylo urpmi instalováno, nemusí však mít definované zdroje). \fIalias\fP definuje, který rozšiřující modul pro urpmi se má použít (v současné době se může jednat o \fBurpmi-parallel-ka-run\fP nebo \fBurpmi-parallel-ssh\fP) a které počítače by měly být aktualizovány. Tento alias je definován v souboru /etc/urpmi/parallel.cfg, jak je popsáno níže.
.IP "\fB\--wget\fP"
pro stahování vzdálených souborů se použije výhradně program wget. Implicitně se používá program curl a program wget pouze tehdy, pokud curl není k dispozici.
.IP "\fB\--curl\fP"
pro stahování vzdálených souborů se použije výhradně program curl. Implicitně se používá program curl a program wget pouze tehdy, pokud curl není k dispozici.
.IP "\fB\--limit-rate\fP \fIrychlost\fP"
pokusí se omezit rychlost stahování, \fIrychlost\fP se zadává v b/s. Tato volba není implicitně aktivní.
.IP "\fB\--proxy\fP \fIproxyhost[:port|1080]\fP"
použije zadanou HTTP proxy.
.IP "\fB\--proxy-user\fP \fIuživatel:heslo\fP"
použije zadaného uživatele a heslo pro ověření na proxy.
.IP "\fB\--bug\fP \fIadresář\fP"
vytvoří hlášení o chybě v \fIadresáři\fP. Toto chybové hlášení je nutné komprimované poslat správci programu urpmi, který ho (doufejme) opraví.
.IP "\fB\--env\fP \fIadresář\fP"
použije odlišné prostředí přímo z hlášení o chybě, aby bylo možné zopakovat chybu, parametry jsou shodné s parametry pro volbu \fB\--bug\fP
.IP "\fB\--X\fP"
použije grafické rozhraní X.
.IP "\fB\--best-output\fP"
pokusí se použít grafické rozhraní X, nebo, pokud není k dispozici, standardní textové rozhraní (za použití programu rpm).
.IP "\fB\--verify-rpm\fP"
aktivuje (výchozí) nebo vypne kontrolu podpisů balíčků RPM.
.IP "\fB\--test\fP"
otestuje (stejně jako příkaz \fBrpm --test\fP) instalaci balíčků, ale neprovede žádný zásah do systému.
.IP "\fB\--excludepath\fP \fIřetězec\fP"
nebude instalovat soubory, jejichž název začíná na zadaný \fIřetězec\fP (stejné jako příkaz \fBrpm --excludepath\fP).
.IP "\fB\--excludedocs\fP"
nenainstaluje soubory s dokumentací (stejné jako příkaz \fBrpm --excludedocs\fP).
.IP "\fB\-a\fP"
pokud zadané části řetězce vyhovuje více balíčků, použije všechny.
.IP "\fB\-p\fP"
umožní prohledávání v tom, co balíček poskytuje (značka provides), a tak nalézt potřebný balíček.
.IP "\fB\-P\fP"
nebude hledat v tom, co balíček poskytuje (značka provides), a tak nalézt potřebný balíček (opak přepínače \fB\-p\fP).
.IP "\fB\-y\fP"
Stejné jako přepínač \fB\--fuzzy\fP.
.IP "\fB\-s\fP"
Stejné jako přepínač \fB\--src\fP.
.IP "\fB\-q\fP"
navrhne při volání programu rpm tichý režim, kde nejsou vypisovány informace o stavu aktualizace.
.IP "\fB\-v\fP"
navrhne užvaněný režim s mnoha různými zprávami.
.SH SOUBORY
/usr/bin/urpmi
.br
Spustitelný soubor \fBurpmi\fP (skript jazyka Perl)
.PP
/var/lib/urpmi/list.*
.br
Obsahuje seznam všech balíčků známých programu urpmi a jejich umístění, pouze pokud je použito heslo pro přístup ke vzdáleným lokacím (pomocí síťového protokolu), nebo různé adresáře, které jsou použity k uložení balíčků.
.PP
/var/lib/urpmi/hdlist.*
.br
Obsahuje informace o všech známých balíčcích, je to souhrn hlaviček balíčků RPM. Pokud je pro zdroj použit soubor hdlist, může program \fBurpmf\fP kompletně fungovat, což je také nejčastější případ. (Více viz manuálové stránky pro příkaz \fBurpmf\fP).
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Obsahuje informace syntézy o všech známých balíčcích, které jsou sestaveny ze souborů hdlist, a které mohou být použity pro urychlení zpracování vašich požadavků. Pokud nejsou tyto soubory přítomny, použijí se soubory hdlist, což je ovšem výrazně pomalejší.
.PP
/etc/urpmi/urpmi.cfg
.br
Obsahuje informace o zdrojích. Je přijímán i formát ze starších verzí programu urpmi.
.PP
/etc/urpmi/parallel.cfg
.br
Obsahuje popis paralelních aliasů ve formátu \fB<alias>:<rozhraní[(zdroje)]>:<parametr_rozhraní>\fP, kde \fB<alias>\fP je symbolický název, \fB<rozhraní>\fP může nabývat hodnot \fBka-run\fP nebo \fBssh\fP, \fB<zdroje>\fP je seznam zdrojů (jako u volby \fB\--media\fP), \fB<parametr_rozhraní>\fP je seznam parametrů specifický pro rozhraní, například "-c ssh -m node1 -m node2" pro rozhraní \fBka-run\fP nebo "node1:node2" pro rozhraní \fBssh\fP.
.PP
/etc/urpmi/skip.list
.br
Obsahuje výrazy s názvy balíčků, které by neměly být automaticky aktualizovány. Formát je tvořen seznamem toho, co balíček poskytuje (nebo regulárním výrazem, pokud je ohraničen lomítky \fB/\fP) s volitelným operátorem a řetězcem s verzí, nebo regulárním výrazem odpovídajícím úplnému názvu balíčku.
.PP
/etc/urpmi/inst.list
.br
Obsahuje názvy balíčků, které by měly být instalovány a ne aktualizovány.
.SH "NÁVRATOVÉ KÓDY"
.IP "\fB1\fP"
Nekonzistence na příkazovém řádku.
.IP "\fB2\fP"
Problém s registrací lokálního balíčku.
.IP "\fB3\fP"
Zdrojový balíček nelze získat.
.IP "\fB4\fP"
Zdroj není vybrán.
.IP "\fB5\fP"
Zdroj již existuje.
.IP "\fB6\fP"
Nelze uložit nastavení.
.IP "\fB7\fP"
Databáze urpmi je zamčená.
.IP "\fB8\fP"
Nelze vytvořit hlášení o chybě.
.IP "\fB9\fP"
Nelze otevřít databázi rpmdb.
.IP "\fB10\fP"
Některé soubory pro instalaci chybí.
.IP "\fB11\fP"
Některé transakce selhaly, ale ne všechny.
.IP "\fB12\fP"
Všechny transakce selhaly.
.IP "\fB13\fP"
Některé soubory chybí a některé transakce selhaly, ale ne všechny.
.IP "\fB14\fP"
Některé soubory chybí a všechny transakce selhaly.
.SH "HLÁŠENÍ O CHYBĚ"
Pokud naleznete v programu \fBurpmi\fP chybu, nahlaste ji prosím pomocí příkazu \fIurpmi --bug název_chyby_jako_adresář ...\fP na příkazové řádce. Bude automaticky vytvořen adresář \fInázev_chyby_jako_adresář\fP obsahující soubory nutné pro zopakování chyby, pokud je to možné.
.PP
Otestujte prosím hlášení o chybě pomocí příkazu \fIurpmi --env název_chyby_jako_adresář ...\fP a zkontrolujte, zda-li dojde znovu k téže chybě. V současné době lze reprodukovat pouze chyby v řešení závislostí.
.PP
Chcete-li hlášení o chybě poslat, použijte příkaz \fItar cvzf název_chyby_jako_adresář.tgz název_chyby_jako_adresář\fP a pošlete výsledný soubor přímo na adresu  s popisem toho, co je podle vás špatně.
.SH "CHYBY"
Pokud je balíček odstraněn, nelze jej nahradit starší verzí.
.SH "VIZ TAKÉ"
urpmi.addmedia(8),
urpmi.update(8),
urpmi.removemedia(8),
urpmf(8),
urpmq(8),
.SH AUTOR
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com> (původní autor)
.br
Francois Pons, Mandrakesoft 
.br
Rafael Garcia-Suarez, Mandrakesoft 
