.TH urpmi.update 8 "28 Srp 2003" "Mandrakesoft" "Mandrakelinux"
.IX urpmi.update
.SH NÁZEV
urpmi.update \- Aktualizuje seznam balíčků pro zadané zdroje
.SH SYNAPSE
.B urpmi.update \fB[volby]\fP \fB[<\fInázvy\fP>]\fP
.SH POPIS
Program urpmi.update zkoumá všechny zdroje se zadanými <\fInázvy\fP> a aktualizuje jejich seznam balíčků. To je užitečné například pro zdroje s umístěním na serverech FTP.
.PP
<\fInázvy\fP> je seznam názvů zdrojů, které jste předtím zadali pomocí programu urpmi.addmedia

.SH VOLBY
.IP "\fB\--wget\fP"
pro stahování vzdálených souborů se použije výhradně program wget. Implicitně se používá program curl a program wget pouze tehdy, pokud curl není k dispozici.
.IP "\fB\--curl\fP"
pro stahování vzdálených souborů se použije výhradně program curl. Implicitně se používá program curl a program wget pouze tehdy, pokud curl není k dispozici.
.IP "\fB\--limit-rate\fP \fIrychlost\fP"
pokusí se omezit rychlost stahování, \fIrychlost\fP se zadává v b/s. Tato volba není implicitně aktivní.
.IP "\fB\--proxy\fP \fIproxyhost[:port|1080]\fP"
použije zadanou HTTP proxy.
.IP "\fB\--proxy-user\fP \fIuživatel:heslo\fP"
použije zadaného uživatele a heslo pro ověření na proxy.
.IP "\fB\--update\fP"
budou se aktualizovat pouze zdroje určené pro aktualizaci.
.IP "\fB\-a\fP"
vybere pro aktualizaci všechny zdroje, které nepoužívají vyjímatelná média.
.IP "\fB\-c\fP"
vyčistí při svém ukončení adresář /var/cache/urpmi/headers.
.IP "\fB\-d\fP"
přinutí ke kompletnímu výpočtu (již nepoužívaného) souboru /var/lib/urpmi/depslist.ordered.
.IP "\fB\-f\fP"
přinutí program urpmi.update znovu vytvořit soubory hdlist.
.SH SOUBORY
/usr/bin/urpmi.update
.br
Spustitelný soubor \fBurpmi.update\fP (skript jazyka Perl)
.PP
/var/lib/urpmi/list.*
.br
Obsahuje seznam všech balíčků známých programu urpmi a jejich umístění, pouze pokud je použito heslo pro přístup ke vzdáleným lokacím (pomocí síťového protokolu), nebo různé adresáře, které jsou použity k uložení balíčků.
.PP
/var/lib/urpmi/hdlist.*
.br
Obsahuje informace o všech známých balíčcích, je to souhrn hlaviček balíčků RPM. Pokud je pro zdroj použit soubor hdlist, může program \fBurpmf\fP kompletně fungovat, což je také nejčastější případ. (Více viz manuálové stránky pro příkaz \fBurpmf\fP).
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Obsahuje informace syntézy o všech známých balíčcích, které jsou sestaveny ze souborů hdlist, a které mohou být použity pro urychlení zpracování vašich požadavků. Pokud nejsou tyto soubory přítomny, použijí se soubory hdlist, což je ovšem výrazně pomalejší.
.PP
/etc/urpmi/urpmi.cfg
.br
Obsahuje informace o zdrojích. Je přijímán i formát ze starších verzí programu urpmi.
.PP
/etc/urpmi/parallel.cfg
.br
Obsahuje popis paralelních aliasů ve formátu \fB<alias>:<rozhraní[(zdroje)]>:<parametr_rozhraní>\fP, kde \fB<alias>\fP je symbolický název, \fB<rozhraní>\fP může nabývat hodnot \fBka-run\fP nebo \fBssh\fP, \fB<zdroje>\fP je seznam zdrojů (jako u volby \fB\--media\fP), \fB<parametr_rozhraní>\fP je seznam parametrů specifický pro rozhraní, například "-c ssh -m node1 -m node2" pro rozhraní \fBka-run\fP nebo "node1:node2" pro rozhraní \fBssh\fP.
.PP
/etc/urpmi/skip.list
.br
Obsahuje výrazy s názvy balíčků, které by neměly být automaticky aktualizovány. Formát je tvořen seznamem toho, co balíček poskytuje (nebo regulárním výrazem, pokud je ohraničen lomítky \fB/\fP) s volitelným operátorem a řetězcem s verzí, nebo regulárním výrazem odpovídajícím úplnému názvu balíčku.
.PP
/etc/urpmi/inst.list
.br
Obsahuje názvy balíčků, které by měly být instalovány a ne aktualizovány.
.SH "VIZ TAKÉ"
urpmi(8),
urpmi.addmedia(8),
urpmf(8),
urpmq(8),
.SH AUTOR
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com> (původní autor)
.br
Francois Pons, Mandrakesoft 
.br
Rafael Garcia-Suarez, Mandrakesoft 
