.TH urpmq 8 "28 Srp 2003" "MandrakeSoft" "Mandrake Linux"
.IX urpmq
.SH "NÁZEV"
urpmq \- nástroj pro dotazy na databázi urpmi.
.SH SYNAPSE
.B urpmq [\fIvolby\fP] [\fInázev_balíèku\fP | \fIsoubory_rpm...\fP]
.SH POPIS
Program urpmq umo¾òuje dotazy na databázi urpmi. Je vám k dispozici, pokud potøebujete zjistit seznam balíèkù dostupných na rùzných zdrojích registrovaných v programu urpmi, nebo pokud potøebujete vypsat závislosti balíèkù, nebo balíèky, které se nainstalují, pokud spustíte program urpmi.
.PP
Výstupní formát programu urpmi se li¹í podle následujících parametrù z pøíkazové øádky:
.IP
[skupina/]název_balíèku[-verze][-vydání][.arch]
.SH VOLBY
.IP "\fB\--help\fP"
zobrazí nápovìdu a ukonèí se (stejné jako \fB\-h\fP nebo \fB\-?\fP).
.IP "\fB\--update\fP"
pou¾ije pouze zdroje pro aktualizaci. To znamená, ¾e program \fBurpmq\fP bude hledat a øe¹it závislosti pouze v rámci zdrojù oznaèených pro aktualizaci.
.IP "\fB\--media\fP \fIzdroj1,...,zdrojN\fP"
pou¾ije pouze zadané zdroje, nikoli v¹echny dostupné zdroje (nebo zdroje pro aktualizaci, pokud je zadána volba \fB\--update\fP).
.IP "\fB\--excludemedia\fP \fIzdroj1,...,zdrojN\fP"
nepou¾ije zadané zdroje.
.IP "\fB\--sortmedia\fP \fIzdroj1,...,zdrojN\fP"
setøídí zadané zdroje, ke zjednodu¹ení seskupení lze pou¾ít podøetìzce.
.IP "\fB\--synthesis\fP \fIsoubor\fP"
pro vyhledávání v balíècích a øe¹ení závislostí pou¾ije místo databáze urpmi zadaný \fIsoubor\fP syntézy.
.IP "\fB\--auto-select\fP"
automaticky vybere v¹echny balíèky, které by mìly být aktualizovány, na základì ji¾ instalovaných balíèkù a balíèkù v seznamech jednotlivých registrovaných zdrojù.
.IP "\fB\--fuzzy\fP"
vypne rychlé hledání pøesného názvu balíèku, jinými slovy navrhne v¹echny balíèky obsahující zadaný název, i pokud existuje takový, který má zadaný název (tato volba je stejná jako volba \fB\-y\fP.
.IP "\fB\--keep\fP"
zmìní výbìr balíèkù, pokud nemohou být uspokojeny nìkteré závislosti tak, ¾e se pokusí ponechat existující balíèky místo toho, aby je odstranil. Toto chování obecnì odmítne aktualizaci balíèkù zadaných na pøíkazové øádce (nebo pøi pou¾ití volby --auto-select), pokud dojde k chybì v závislostech.
.IP "\fB\--list\fP"
vypí¹e dostupné balíèky.
.IP "\fB\--list-media\fP"
vypí¹e dostupné zdroje.
.IP "\fB\--list-nodes\fP"
vypí¹e dostupné poèítaèe, pokud je pou¾ita volba \fB\--parallel\fP.
.IP "\fB\--list-aliases\fP"
vypí¹e seznam dostupných paralelních aliasù.
.IP "\fB\--src\fP \fInázev\fP"
prohledává zdrojový balíèek podle \fInázvu\fP a implicitnì vybere v¹echny závislosti, pokud není zadaná volba \fB\--install-src\fP pro instalaci zdrojového balíèku samotného.
.IP "\fB\--headers\fP"
získá hlavièky vybraných balíèkù a vypí¹e je na standardní výstup.
.IP "\fB\--sources\fP"
vypí¹e zdrojové url (nebo soubor) v¹ech vybraných balíèkù.
.IP "\fB\--force\fP"
bude ignorovat výskyt chyby, pokud jsou vy¾ádány neexistující balíèky.
.IP "\fB\--parallel\fP \fIalias\fP"
aktivuje distribuované spu¹tìní urpmi na dal¹ích poèítaèích (je nutné, aby na tìchto poèítaèích bylo urpmi instalováno, nemusí v¹ak mít definované zdroje). \fIalias\fP definuje, který roz¹iøující modul pro urpmi se má pou¾ít (v souèasné dobì se mù¾e jednat o \fBurpmi-parallel-ka-run\fP nebo \fBurpmi-parallel-ssh\fP) a které poèítaèe by mìly být aktualizovány. Tento alias je definován v souboru /etc/urpmi/parallel.cfg, jak je popsáno ní¾e.
.IP "\fB\--wget\fP"
pro stahování vzdálených souborù se pou¾ije výhradnì program wget. Implicitnì se pou¾ívá program curl a program wget pouze tehdy, pokud curl není k dispozici.
.IP "\fB\--curl\fP"
pro stahování vzdálených souborù se pou¾ije výhradnì program curl. Implicitnì se pou¾ívá program curl a program wget pouze tehdy, pokud curl není k dispozici.
.IP "\fB\--proxy\fP \fIproxyhost[:port|1080]\fP"
pou¾ije zadanou HTTP proxy.
.IP "\fB\--proxy-user\fP \fIu¾ivatel:heslo\fP"
pou¾ije zadaného u¾ivatele a heslo pro ovìøení na proxy.
.IP "\fB\--env\fP \fIadresáø\fP"
pou¾ije odli¹né prostøedí pøímo z hlá¹ení o chybì, aby bylo mo¾né zopakovat chybu, parametry jsou shodné s parametry pro volbu \fB\--bug\fP
.IP "\fB\-v\fP"
aktivuje u¾vanìný re¾im.
.IP "\fB\-d\fP"
vybere závislosti (maximální mno¾ina).
.IP "\fB\-u\fP"
zru¹í výbìr balíèkù, pokud je ji¾ instalovaná novìj¹í verze. Tuto volbu lze pou¾ít s volbou \fB\-d\fP a tím simulovat re¾im \fB\-M\fP programu \fBurpmi\fP.
.IP "\fB\-a\fP"
vybere v¹echny shody z pøíkazového øádku, u¾iteèné pøi pou¾ití voleb \fB\-f\fP nebo \fB\-r\fP, pokud je zadán neúplný název.
.IP "\fB\-c\fP"
pokud je vybrána maximální mno¾ina závislostí, bude program pøedpokládat, ¾e uvedené balíèky mají chybné nebo zastaralé závislosti. To zpùsobí, ¾e se bude aktualizovat více balíèkù, ale mù¾e tím opravit nevyøe¹ené závislosti uvnitø databáze rpm.
.IP "\fB\-p\fP"
umo¾ní prohledávat znaèky provides a nalézt tak potøebný balíèek.
.IP "\fB\-P\fP"
nebude hledat v tom, co balíèek poskytuje (znaèka provides), a tak nalézt potøebný balíèek (opak pøepínaèe \fB\-p\fP).
.IP "\fB\-R\fP"
obrátí hledání na to, co balíèek poskytuje.
.IP "\fB\-y\fP"
Stejné jako pøepínaè \fB\--fuzzy\fP.
.IP "\fB\-s\fP"
Stejné jako pøepínaè \fB\--src\fP.
.IP "\fB\-g\fP"
vypí¹e skupinu, do které patøí ka¾dý z vybraných balíèkù.
.IP "\fB\-r\fP"
vypí¹e verzi a vydání ka¾dého z vybraných balíèkù.
.IP "\fB\-f\fP"
vypí¹e verzi, vydání a architekturu ka¾dého z vybraných balíèkù.
.SH SOUBORY
/usr/bin/urpmq
.br
Spustitelný soubor \fBurpmq\fP (skript jazyka Perl)
.PP
/var/lib/urpmi/list.*
.br
Obsahuje seznam v¹ech balíèkù známých programu urpmi a jejich umístìní, pouze pokud je pou¾ito heslo pro pøístup ke vzdáleným lokacím (pomocí sí»ového protokolu), nebo rùzné adresáøe, které jsou pou¾ity k ulo¾ení balíèkù.
.PP
/var/lib/urpmi/hdlist.*
.br
Obsahuje informace o v¹ech známých balíècích, je to souhrn hlavièek balíèkù RPM. Pokud je pro zdroj pou¾it soubor hdlist, mù¾e program \fBurpmf\fP kompletnì fungovat, co¾ je také nejèastìj¹í pøípad. (Více viz manuálové stránky pro pøíkaz \fBurpmf\fP).
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Obsahuje informace syntézy o v¹ech známých balíècích, které jsou sestaveny ze souborù hdlist, a které mohou být pou¾ity pro urychlení zpracování va¹ich po¾adavkù. Pokud nejsou tyto soubory pøítomny, pou¾ijí se soubory hdlist, co¾ je ov¹em výraznì pomalej¹í.
.PP
/etc/urpmi/urpmi.cfg
.br
Obsahuje informace o zdrojích. Je pøijímán i formát ze star¹ích verzí programu urpmi.
.PP
/etc/urpmi/parallel.cfg
.br
Obsahuje popis paralelních aliasù ve formátu \fB<alias>:<rozhraní[(zdroje)]>:<parametr_rozhraní>\fP, kde \fB<alias>\fP je symbolický název, \fB<rozhraní>\fP mù¾e nabývat hodnot \fBka-run\fP nebo \fBssh\fP, \fB<zdroje>\fP je seznam zdrojù (jako u volby \fB\--media\fP), \fB<parametr_rozhraní>\fP je seznam parametrù specifický pro rozhraní, napøíklad "-c ssh -m node1 -m node2" pro rozhraní \fBka-run\fP nebo "node1:node2" pro rozhraní \fBssh\fP.
.PP
/etc/urpmi/skip.list
.br
Obsahuje výrazy s názvy balíèkù, které by nemìly být automaticky aktualizovány. Formát je tvoøen seznamem toho, co balíèek poskytuje (nebo regulárním výrazem, pokud je ohranièen lomítky \fB/\fP) s volitelným operátorem a øetìzcem s verzí, nebo regulárním výrazem odpovídajícím úplnému názvu balíèku.
.PP
/etc/urpmi/inst.list
.br
Obsahuje názvy balíèkù, které by mìly být instalovány a ne aktualizovány.
.SH "VIZ TAKÉ"
urpmi(8),
urpmi.addmedia(8),
urpmi.update(8),
urpmi.removemedia(8),
urpmf(8),
.SH AUTOR
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com> (pùvodní autor)
.br
Francois Pons, Mandrakesoft <fpons@mandrakesoft.com>
.br
Rafael Garcia-Suarez, Mandrakesoft <rgarciasuarez@mandrakesoft.com>
