/* this is a placeholder so that xgettext can find the translatable
 * strings. This file is automatically generated, look at
 * ./create_placeholder
 */
char *foobar[] = { 
N_("urpmf version %s"),
N_("Copyright (C) 1999,2000,2001 MandrakeSoft."),
N_("This is free software and may be redistributed under the terms of the GNU GPL."),
N_("usage: urpmf [options] <file>"),
N_("  --quiet         - do not print tag name (default if no tag given on command"),
N_("                    line, incompatible with interactive mode)."),
N_("  --all           - print all tags."),
N_("  --name          - print tag name: rpm filename (assumed if no tag given on"),
N_("                    command line but without package name)."),
N_("  --group         - print tag group: group."),
N_("  --size          - print tag size: size."),
N_("  --serial        - print tag serial: serial."),
N_("  --summary       - print tag summary: summary."),
N_("  --description   - print tag description: description."),
N_("  --provides      - print tag provides: all provides (mutliple lines)."),
N_("  --requires      - print tag requires: all requires (multiple lines)."),
N_("  --files         - print tag files: all files (multiple lines)."),
N_("  --conflicts     - print tag conflicts: all conflicts (multiple lines)."),
N_("  --obsoletes     - print tag obsoletes: all obsoletes (multiple lines)."),
N_("  --prereqs       - print tag prereqs: all prereqs (multiple lines)."),
N_("usage: urpmf [options] <file>"),
N_("try urpmf --help for more options"),
N_("urpmi is not installed"),
N_("incoherent list file for \"%s\", medium ignored"),
N_("relocated %s entries in depslist"),
N_("copy of [%s] failed"),
N_("unable to read rpm file [%s] from medium \"%s\""),
N_("invalid rpm file name [%s]"),
N_("source of [%s] not found as [%s]"),
N_("unable to write compss file [%s]"),
N_("selecting %s using obsoletes"),
N_("unmounting %s"),
N_("unable to access list file of \"%s\", medium ignored"),
N_("write compss file [%s]"),
N_("trying to remove inexistant medium \"%s\""),
N_("medium \"%s\" is not selected"),
N_("read depslist file [%s]"),
N_("built hdlist synthesis file for medium \"%s\""),
N_("read provides file [%s]"),
N_("unable to take care of medium \"%s\" as list file is already used by another medium"),
N_("nothing written in list file for \"%s\""),
N_("unable to write depslist file [%s]"),
N_("computing dependencies"),
N_("unable to write provides file [%s]"),
N_("wget of [%s] failed"),
N_("incoherent medium \"%s\" marked removable but not really"),
N_("write depslist file [%s]"),
N_("keeping only provides files"),
N_("trying to select inexistant medium \"%s\""),
N_("no hdlist file found for medium \"%s\""),
N_("no package named %s"),
N_("The following packages contain %s: %s"),
N_("write provides file [%s]"),
N_("medium \"%s\" try to use an already used hdlist, medium ignored"),
N_("avoid selecting %s as its locales language is not already selected"),
N_("wget of [%s] failed (maybe wget is missing?)"),
N_("mismatch arch for registering rpm file"),
N_("unable to write list file of \"%s\""),
N_("removing %d obsolete headers in cache"),
N_("error registering local packages"),
N_("trying to bypass existing medium \"%s\", avoiding"),
N_("unable to build synthesis file for medium \"%s\""),
N_(""
"removing %s to upgrade ...\n"
" to %s since it will not be updated otherwise"
""),
N_("no rpm files found from [%s]"),
N_("read compss file [%s]"),
N_("unable to inspect list file for \"%s\", medium ignored"),
N_("unable to build hdlist: %s"),
N_("selecting %s by selection on files"),
N_("unable to write config file [%s]"),
N_("found %d headers in cache"),
N_("unable to read depslist file [%s]"),
N_("unable to copy source of [%s] from [%s]"),
N_("malformed input: [%s]"),
N_("write config file [%s]"),
N_("unable to read provides file [%s]"),
N_("syntax error in config file at line %s"),
N_("removable medium not selected"),
N_("unable to access hdlist file of \"%s\", medium ignored"),
N_("package %s is not found."),
N_("unable to determine medium of this hdlist file [%s]"),
N_("unknown data associated with %s"),
N_("medium \"%s\" try to use an already used list, medium ignored"),
N_("unable to take medium \"%s\" into account as no list file [%s] exists"),
N_("rpmtools package is too old, please upgrade it"),
N_("building hdlist [%s]"),
N_("unable to access medium \"%s\""),
N_("mounting %s"),
N_("unable to use name \"%s\" for unamed medium because it is already used"),
N_("unable to find all synthesis file, using parsehdlist server"),
N_("unable to access rpm file [%s]"),
N_("avoid selecting %s as not enough files will be updated"),
N_("unable to parse hdlist file of \"%s\""),
N_("retrieving [%s]"),
N_("unable to find list file for \"%s\", medium ignored"),
N_("mismatch release for registering rpm file"),
N_(""
"removing %s to upgrade ...\n"
" to %s since it will not upgrade correctly!"
""),
N_("reading hdlist file [%s]"),
N_("unable to parse correctly [%s] on value \"%s\""),
N_("mismatch version for registering rpm file"),
N_("nothing to write in list file for \"%s\""),
N_("unable to find hdlist file for \"%s\", medium ignored"),
N_("unable to read compss file [%s]"),
N_("unable to parse correctly [%s]"),
N_("there are multiples packages with the same rpm filename \"%s\""),
N_("medium \"%s\" already exists"),
N_("What is your choice? (1-%d) "),
N_("One of the following packages is needed:"),
N_("Press enter when it's done..."),
N_("Cancel"),
N_("everything already installed"),
N_(" (Y/n) "),
N_("To satisfy dependencies, the following packages are going to be installed (%d MB)"),
N_("unable to get source packages, aborting"),
N_("Try installation without checking dependencies? (y/N) "),
N_("Please insert the medium named \"%s\" on device [%s]"),
N_(""
"urpmi version %s\n"
"Copyright (C) 1999, 2000, 2001 MandrakeSoft.\n"
"This is free software and may be redistributed under the terms of the GNU GPL.\n"
"usage:\n"
"  --help           - print this help message.\n"
"  --update         - use only update media.\n"
"  --auto           - automatically select a good package in choices.\n"
"  --auto-select    - automatically select packages for upgrading the system.\n"
"  --force          - force invocation even if some package do not exist.\n"
"  --X              - use X interface.\n"
"  --best-output    - choose best interface according to the environment:\n"
"                     X or text mode.\n"
"  -a               - select all matches on command line.\n"
"  -m               - choose minimum closure of requires (default).\n"
"  -M               - choose maximun closure of requires.\n"
"  -c               - choose complete method for resolving requires closure.\n"
"  -p               - allow search in provides to find package.\n"
"  -q               - quiet mode.\n"
"  -v               - verbose mode.\n"
"  names or rpm files (only for root) given on command line are installed.\n"
""),
N_("Sorry, bad choice, try again\n"),
N_("Is it ok?"),
N_("Yy"),
N_("Try installation even more strongly (--force)? (y/N) "),
N_("installing %s\n"),
N_("Installation failed"),
N_("Only superuser is allowed to install local packages"),
N_("Ok"),
N_("Nn"),
N_(""
"%s\n"
"`with' missing for ftp media\n"
""),
N_("unable to update medium \"%s\"\n"),
N_(""
"%s\n"
"device `%s' do not exist\n"
""),
N_("unable to create medium \"%s\"\n"),
N_(""
"usage: urpmi.addmedia [--update] <name> <url>\n"
"where <url> is one of\n"
"       file://<path>\n"
"       ftp://<login>:<password>@<host>/<path> with <relative filename of hdlist>\n"
"       ftp://<host>/<path> with <relative filename of hdlist>\n"
"       http://<host>/<path> with <relative filename of hdlist>\n"
"       removable_<device>://<path>\n"
""),
N_(""
"%s\n"
"<relative path of hdlist> missing\n"
""),
N_(""
"the entry to update is missing\n"
"(one of %s)\n"
""),
N_("nothing to update (use urpmi.addmedia to add a media)\n"),
N_(""
"usage: urpmi.update [-a] <name> ...\n"
"where <name> is a medium name to update.\n"
"   -a    select all non-removable media.\n"
"   -c    clean headers cache directory.\n"
"   -f    force generation of base files, use another -f for hdlist files.\n"
"\n"
"unknown options '%s'\n"
""),
N_(""
"usage: urpmi.removemedia [-a] <name> ...\n"
"where <name> is a medium name to remove.\n"
"   -a    select all media.\n"
"\n"
"unknown options '%s'\n"
""),
N_("nothing to remove (use urpmi.addmedia to add a media)\n"),
N_(""
"the entry to remove is missing\n"
"(one of %s)\n"
""),
N_("urpmq: unknown option \"-%s\", check usage with --help\n"),
N_(""
"urpmq version %s\n"
"Copyright (C) 2000, 2001 MandrakeSoft.\n"
"This is free software and may be redistributed under the terms of the GNU GPL.\n"
"usage:\n"
"  -h             - print this help message.\n"
"  -v             - verbose mode.\n"
"  -d             - extend query to package dependencies.\n"
"  -u             - remove package if a better version is already installed.\n"
"  -m             - extend query to package dependencies, remove already\n"
"                   installed package that provide what is necessary, add\n"
"                   packages that may be block the upgrade.\n"
"  -M             - extend query to package dependencies and remove already\n"
"                   installed package only if they are newer or the same.\n"
"  -c             - choose complete method for resolving requires closure.\n"
"  -p             - allow search in provides to find package.\n"
"  -g             - print groups too with name.\n"
"  -r             - print version and release too with name.\n"
"  --update       - use only update media.\n"
"  --auto-select  - automatically select packages for upgrading the system.\n"
"  --headers      - extract headers for package listed from urpmi db to\n"
"                   stdout (root only).\n"
"  --sources      - give all source packages before downloading (root only).\n"
"  --force        - force invocation even if some package do not exist.\n"
"  names or rpm files given on command line are queried.\n"
""),
N_("some package have to be removed for being upgraded, this is not supported yet\n"),
N_("urpmq: cannot read rpm file \"%s\"\n"),
N_("unable to get source packages, aborting"),
};
