/* this is a placeholder so that xgettext can find the translatable
 * strings. This file is automatically generated, look at
 * ./create_placeholder
 */
char *foobar[] = { 
N_("urpmf version %s"),
N_("Copyright (C) 1999,2000,2001 MandrakeSoft."),
N_("This is free software and may be redistributed under the terms of the GNU GPL."),
N_("usage: urpmf [options] <file>"),
N_("  --quiet         - do not print tag name (default if no tag given on command"),
N_("                    line, incompatible with interactive mode)."),
N_("  --all           - print all tags."),
N_("  --name          - print tag name: rpm filename (assumed if no tag given on"),
N_("                    command line but without package name)."),
N_("  --group         - print tag group: group."),
N_("  --size          - print tag size: size."),
N_("  --serial        - print tag serial: serial."),
N_("  --summary       - print tag summary: summary."),
N_("  --description   - print tag description: description."),
N_("  --provides      - print tag provides: all provides (mutliple lines)."),
N_("  --requires      - print tag requires: all requires (multiple lines)."),
N_("  --files         - print tag files: all files (multiple lines)."),
N_("  --conflicts     - print tag conflicts: all conflicts (multiple lines)."),
N_("  --obsoletes     - print tag obsoletes: all obsoletes (multiple lines)."),
N_("  --prereqs       - print tag prereqs: all prereqs (multiple lines)."),
N_("usage: urpmf [options] <file>"),
N_("try urpmf --help for more options"),
N_("urpmi is not installed"),
};
