.TH proxy.cfg 5 "25 Aug 2004" "Mandriva" "Mandriva Linux"
.IX proxy.cfg
.SH NAME
proxy.cfg \- urpmi proxy configuration file format.
.SH DESCRIPTION
The proxy.cfg file contains lines of the form

.B "[media:]http_proxy=[value]"

.B "[media:]ftp_proxy=[value]"

.B "[media:]proxy_user=[value]"

where the media part is optional (in this case, the line applies
to all media).

ftp_proxy and http_proxy values have the same syntax as the usual
environment variables used by many programs such as \fIcurl\fP(1):

.B "[protocol://]<host>[:port]"

proxy_user values are simply a user name, or a user name and a
password separated by a colon (:).

.SH AUTHOR
Francois Pons
.PP
Rafael Garcia-Suarez 
(current maintainer)
.SH SEE ALSO
\fIurpmi\fP(8), \fIurpmi.cfg\fP(5), \fIurpmi.files\fP(5).
