.TH urpmi 8 "08 Jan 2003" "MandrakeSoft" "Mandrake Linux"
.IX urpmi
.SH NAME
urpmi \- rpm wrapper making installs easier for the user
.SH SYNOPSIS
.B urpmi [\fIoptions\fP] [\fIpackage_names\fP | \fIrpm_files...\fP]
.SH DESCRIPTION
urpmi authorizes well-known rpms (or rpm files) to be installed including
all their dependencies.
You can use it to install source package dependencies or source package itself.

You can compare rpm vs. urpmi  with  insmod vs. modprobe or dpkg vs apt-get
.PP
Just launch urpmi followed by what you think is the name of the package(s),
and urpmi will:
.br
\- Propose different package names if availables and quit.
.br
\- If only one corresponding package is found, check whether dependencies are 
already installed, or not.
.br
\- If not, propose to install the dependencies and then install all required
dependencies and the package.
.PP
Note that urpmi handle installations from various medias (ftp, http, local and
nfs volumes, removable medias such as CDROMs) and is able to install
dependencies from a media different from the package's media.
If necessary, urpmi asks you to insert the required media.
.PP
To add a new media containing rpms run urpmi.addmedia.
.br
To remove a media use urpmi.removemedia.
.br
To update the packages list (for example when the ftp archive changed) use
urpmi.update.
.br
To automatically install a package corresponding to an executable you tried
to launch, use autoirpm.
.br
To install all available menu entries of all known packages,
use autoirpm-icons.
.SH OPTIONS
.IP "\fB\--help\fP"
Print an help message and exit (this is the same as \fB-h\fP or \fB-?\fP).
.IP "\fB\--update\fP"
Use only update media. This means \fBurpmi\fP will search and resolve
dependencies only in media marked as update.
.IP "\fB\--media\fP \fImedium1,...,mediumN\fP"
Select specific media to use instead of all media available (or update media is
\fB--update\fP is used).
.IP "\fB\--synthesis\fP \fIfile\fP"
Use the given synthesis\fIfile\fP instead of urpmi db for searching packages and
resolving dependencies.
.IP "\fB\--auto\fP"
Installs all required dependencies without asking.
.IP "\fB\--auto-select\fP"
Automatically select all packages that have to be upgraded according to already
installed packages and packages listed in various media registered.
.IP "\fB\--fuzzy\fP"
Disable fast search on exact package name, ie it will propose all
package containing the name even if one has the given name (this is the same
as \fB\-y\fP).
.IP "\fB\--src\fP \fIname\fP"
Search a source package according to \fIname\fP and it will select all dependencies by
default, unless \fB\--install-src\fP is used in order to install source package
itself.
.IP "\fB\--install-src\fP"
Install only source package (no binary packages will be installed).
.IP "\fB\--clean\fP"
Remove all packages from the cache in directory /var/cache/urpmi/rpms.
.IP "\fB\--noclean\fP"
Do not remove any packages from the cache in directory /var/cache/urpmi/rpms.
.IP "\fB\--force\fP"
Assumes yes on all questions.
.IP "\fB\--allow-nodeps\fP"
Allow urpmi to ask user to continue installation using no dependencies checking
due to error. By default urpmi exit immediately in such case.
.IP "\fB\--allow-force\fP"
Allow urpmi to ask user to continue installation using no dependencies checking
or forced installation due to error. By default urpmi exit immediately in such
case.
.IP "\fB\--parallel\fP \fIalias\fP"
Activate distributed execution of urpmi to other machines (it is mandatory that
urpmi is installed but it is not necessary to have media defined on any
machines). \fIalias\fP defines which extension module to use by urpmi (currently
\fBurpmi-parallel-ka-run\fP or \fBurpmi-parallel-ssh\fP) and which machines
should be updated, this alias is defined in the file /etc/urpmi/parallel.cfg as
described below.
.IP "\fB\--wget\fP"
Use wget only for downloading distant files. By default curl is used if
available or wget instead.
.IP "\fB\--curl\fP"
Use curl only for downloading distant files. By default curl is used if
available or wget instead.
.IP "\fB\--proxy\fP \fIproxyhost[:port|1080]\fP"
Use specified HTTP proxy.
.IP "\fB\--proxy-user\fP \fIuser:password\fP"
Use specified user and password to use for proxy authentication.
.IP "\fB\--bug\fP \fIdirectory\fP"
Create a bug report in \fIdirectory\fP, you have to send a compressed archive of
the directory to \fBurpmi\fP maintainer for the bug being (problably) fixed.
.IP "\fB\--env\fP \fIdirectory\fP"
Use a different environment directly from a bug report to replay a bug, the
argument is the same argument given to \fB--bug\fP option.
.IP "\fB\--X\fP"
Use X interface.
.IP "\fB\--best-output\fP"
Try to use X interface or if not available the standard text interface (using
rpm like output).
.IP "\fB\--verify-rpm\fP" or "\fB\--no-verify-rpm\fP"
Activate (default) or deactivate rpm signature checking.
.IP "\fB\--test\fP"
Test (same as \fBrpm --test\fP) installation of packages but do not modify the
system.
.IP "\fB\--excludepath\fP"
Do not install files whose name begins with path given (same as \fBrpm
--excludepath\fP).
.IP "\fB\-a\fP"
If multiple packages match the substring given, take them all
.IP "\fB\-p\fP"
Allow search in provides to find package (default).
.IP "\fB\-P\fP"
Do not search in provides to find package (this is the opposite of \fB-p\fP).
.IP "\fB\-y\fP"
Yhis is the same as \fB--fuzzy\fP.
.IP "\fB\-s\fP"
This is the same as \fB--src\fP.
.IP "\fB\-q\fP"
Proposes a quiet mode when calling rpm where no upgrade status are printed.
.IP "\fB\-v\fP"
Proposes a verbose mode with various messages.
.SH FILES
.de FN
\fI\|\\$1\|\fP
..
.TP
.FN /usr/sbin/urpmi
The \fBurpmi\fP executable (perl script)
.TP
.FN /var/lib/urpmi/list.*
Contains the list of all packages known by urpmi and their location only
if a password is used to access distant location (using network protocol) or
various directory are used to store packages.
.TP
.FN /var/lib/urpmi/hdlist.*
Contains information about all known packages, it's a summary of rpm headers.
If an hdlist file is used for a medium \fBurpmf\fP can operate completely which
is almost always the case (please refer to \fBurpmf\fP man page for more
informations on this topic).
.TP
.FN /var/lib/urpmi/synthesis.hdlist.*
Contains synthesis information about all known packages built from hdlist files
that can be used by minimal closure algorithm. If these files are not present
hdlist files will be used instead but this is much slower.
.TP
.FN /etc/urpmi/urpmi.cfg
Contains media description, previous format from older urpmi is still accepted.
.TP
.FN /etc/urpmi/parallel.cfg
Contains parallel alias description, format is
\fB<alias>:<interface[(media)]>:<interface_parameter>\fP where \fB<alias>\fP is
a symbolic name, \fB<interface>\fP can be \fBka-run\fP or \fBssh\fP,
\fB<media>\fP is a media list (as \fB--media\fP parameter),
\fB<interface_parameter>\fP is a specific interface parameter list like "-c ssh
-m node1 -m node2" for \fBka-run\fP extension or "node1:node2" for \fBssh\fP
extension.
.TP
.FN /etc/urpmi/skip.list
Contains package expressions that should not be automatically updated. The
format is a list of provide of package (or regular expression if bounded by
slashes \fB/\fP) with optional operator and version string, or regular
expression to match the fullname of packages too.
.TP
.FN /etc/urpmi/inst.list
Contains package names that should be installed instead of updated.
.SH SEE ALSO
\fIurpmi.addmedia\fP(8),
\fIurpmi.update\fP(8),
\fIurpmi.removemedia\fP(8),
\fIgurpmi\fP(8),
\fIurpmf\fP(8),
\fIurpmq\fP(8),
\fIrpmdrake\fP(8)
.SH AUTHOR
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com> (original author)
.PP
Francois Pons, Mandrakesoft <fpons@mandrakesoft.com> (current author)

.SH BUG REPORTS
If you find a bug in \fBurpmi\fP please report it using
.I urpmi --bug bug_name_as_directory ...
command with the command line used, it will automatically create a directory
called \fIbug_name_as_directory\fP containing necessary files to reproduce it if
possible.
.PP
Please test the report using
.I urpmi --env bug_name_as_directory ...
to check bug is still here, currently only resolution bugs are reproduceable.
.PP
For sending the report, use
.I tar cvfz bug_name_as_directory.tgz bug_name_as_directory
and send me (fpons@mandrakesoft.com) it directly with a description of what is
wrong according to you.

.SH BUGS
When a package is removed, it may not be replaced with an older version.
.PP
There is no good download indicator using \fBwget\fP.