.TH urpmq 8 "12 Feb 2001" "MandrakeSoft" "Mandrake Linux"
.IX urpmq
.SH NAME
urpmq \- urpmi database query tool.
.SH SYNOPSIS
.B urpmq [\fIoptions\fP] [\fIpackage_names\fP | \fIrpm_files...\fP]
.SH DESCRIPTION
urpmq allows querying the urpmi database. It is for you if want to list
available packages in the various media of urpmi, or list dependancies of
packages or packages that will be installed if you start urpmi.
.PP
Output format of urpmq is the following according to command line options:
.IP
[group/]package_name[-version][-release][.arch]
.SH OPTIONS
.IP "\fB\--help\fP"
print an help message and exit (this is the same as \fB-h\fP or \fB-?\fP).
.IP "\fB\--update\fP"
use only update media. This means \fBurpmq\fP will search and resolve
dependencies only in media marked as update.
.IP "\fB\--media\fP"
select specific media to use instead of all media available (or update media is
\fB--update\fP is used).
.IP "\fB\--auto-select\fP"
automatically select all packages that have to be upgraded according to already
installed packages and packages listed in various media registered.
.IP "\fB\--fuzzy\fP"
disable fast search on exact package name, ie it will propose all
package containing the name even if one has the given name (this is the same
as \fB\-y\fP).
.IP "\fB\--src\fP"
next package name is a source package and it will select all dependencies if
\fBurpmi\fP is run as root or only install source package as simple user (this
is the same as \fB\-s\fP).
.IP "\fB\--headers\fP"
extract headers for package selected to standard output.
.IP "\fB\--sources\fP"
print source url (or file) of all packages selected.
.IP "\fB\--force\fP"
ignore error of inexistant packages requested.
.IP "\fB\-v\fP"
activate verbose mode.
.IP "\fB\-d\fP"
select dependancies (maximal closure).
.IP "\fB\-u\fP"
deselect packages if a better version is already installed, this option can be
used with \fB-d\fP to simulate \fB-M\fP mode of \fBurpmi\fP.
.IP "\fB\-c\fP"
if maximal closure is used, assume that a package listed mey have wrong or not
up-to-date dependancies. This cause more package to be upgraded and may correct
unresolved dependancies on the rpm database.
.IP "\fB\-p\fP"
allow search in provides to find package.
.IP "\fB\-P\fP"
do not search in provides to find package (this is the opposite of \fB-p\fP and
is the default).
.IP "\fB\-y\fP"
this is the same as \fB--fuzzy\fP.
.IP "\fB\-s\fP"
this is the same as \fB--src\fP.
.IP "\fB\-g\fP"
print group of each packages listed.
.IP "\fB\-r\fP"
print version and release of each packages listed.
.IP "\fB\-f\fP"
print version, release and arch of each packages listed.
.SH FILES
/usr/bin/urpmq
.br
The \fBurpmq\fP executable (perl script)
.PP
/var/lib/urpmi/list.*
.br
Contains the list of all packages known by urpmi and their location.
There is one filelist per media(*).
.PP
/var/lib/urpmi/hdlist.*
.br
Contain information about all known packages, it's a summary of rpm headers.
There is one filelist per media(*).
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Contain synthesis information about all known packages built from hdlist files
that can be used by minimal closure algorithm. If these files are not present
use \fBurpmi.update -a\fP to generate them. These files are not mandatory.
.PP
/etc/urpmi/urpmi.cfg
.br
Contains media description, previous format from older urpmi is accepted.
.PP
/etc/urpmi/skip.list
.br
Contains package names that should be not automatically updated.
.PP
/etc/urpmi/inst.list
.br
Contains package names that should be installed instead of updated.
.SH "SEE ALSO"
urpmi(8),
urpmi.addmedia(8),
urpmi.update(8),
urpmi.removemedia(8),
autoirpm(8),
gurpmi(8),
urpmf(8),
rpmdrake(8)
.SH AUTHOR
Francois Pons, Mandrakesoft
.br
fpons@mandrakesoft.com
