.TH urpmi.addmedia 8 "28 Aug 2003" "Mandriva" "Mandriva Linux"
.IX urpmi.addmedia
.SH NAME
urpmi.addmedia \- adds a new rpm medium to be used by urpmi
.SH SYNOPSIS
.B urpmi.addmedia [\fIoptions\fP] <\fIname\fP> <\fIurl\fP> [with <\fIhdlist\fP>]
.SH DESCRIPTION
urpmi.addmedia tells urpmi that it can find new rpms at the specified location.
Currently supported media types are: local drives, removable drives (such as
CDs), and networked media via different protocols (http, ftp, ssh and rsync).
.PP
One of the following modes must be chosen:
.PP
http:
.IP "\fB urpmi.addmedia [\fIoptions\fP] <\fIname\fP> http://<\fIlogin\fP>:<\fIpass\fP>@<\fIhost\fP>/<\fIpath\fP> [with <\fIrelative path of synthesis|hdlist\fP>]\fP"
Where <\fIname\fP> is your reference for the medium (e.g. "updates").
<\fIname\fP> is optional if \fB--distrib\fP is given in \fIoptions\fP.
.br
<\fIhost\fP>/<\fIpath\fP> is the location of the media directory on the net
(e.g. media/main).
.br
<\fIrelative path of hdlist\fP> is the pathname where to find the hdlist of
the rpms. The location is given relative to <\fIpath\fP>.
.br
\fBcurl\fP is used by default to download files, \fBwget\fP may be used if
\fBcurl\fP is not installed or \fB--curl\fP is given in \fIoptions\fP.
.br
\fIeg\fP: urpmi.addmedia http http://jpackage.sf.net/rpm/free with hdlist.cz
.PP
ftp:
.IP "\fB urpmi.addmedia [\fIoptions\fP] <\fIname\fP> ftp://<\fIlogin\fP>:<\fIpass\fP>@<\fIhost\fP>/<\fIpath\fP> [with <\fIrelative path of synthesis|hdlist\fP>]\fP"
The same as for http, just add your login and user if required (Note that
you don't need to specify \fBanonymous\fP as login for anonymous access ftp
servers).
.br
Note that if \fBwget\fP is used to download files with a firewall you may
have to add the \fBpassive_ftp=on\fP option to \fB/etc/wgetrc\fP. 
.br
\fIeg\fP: urpmi.addmedia ftp ftp://a:a@leia//export/media/main with media_info/hdlist.cz
.PP
ssh:
.IP "\fB urpmi.addmedia [\fIoptions\fP] <\fIname\fP> ssh://<\fIlogin\fP>@<\fIhost\fP>/<\fIpath\fP> [with <\fIrelative path of synthesis|hdlist\fP>]\fP"
The same as for http, just add your login and password if required. It is
strongly recommended to export the root key in order not to have to type a
password all the time. \fBscp\fP and \fBrsync\fP will be used to get files.
.br
\fIeg\fP: urpmi.addmedia -h ssh ssh://fpons@bi/c/i586/media/main
.PP
rsync:
.IP "\fB urpmi.addmedia [\fIoptions\fP] <\fIname\fP> rsync://<\fIlogin\fP>@<\fIhost\fP>:<\fIport\fP>/<\fIpath\fP> [with <\fIrelative path of synthesis|hdlist\fP>]\fP"
The same as for http, you can use <\fIhost\fP>::<\fIpath\fP> too.
.br
\fIeg\fP: urpmi.addmedia rsync rsync://ftp.orst.edu::mandrake-devel/contrib/ppc with ../../cooker/ppc/media/media_info/hdlist2.cz
.PP
Local drive or NFS:
.br
.IP "\fB urpmi.addmedia [\fIoptions\fP] <\fIname\fP> file://<\fIpath\fP>\fP [with <\fIrelative path of synthesis|hdlist\fP>]\fP"
Where <\fIname\fP> is your reference for the medium (e.g. Myrpms).
.br
<\fIpath\fP> is the location of the media directory on your machine
(e.g. media/main).
.PP
Removable device:
.br
.IP "\fB urpmi.addmedia [\fIoptions\fP] <\fIname\fP> removable://<\fIpath\fP>\fP [with <\fIrelative path of synthesis|hdlist\fP>]\fP"
<\fIpath\fP> is the location of the media directory on your machine when the
removable device is mounted. This works for removable drives, but also for ISO
images mounted on a loop device. urpmi will then be able to re-mount the ISO
image to the specified path (but the ISO image must be mounted when you run
\fBurpmi.addmedia\fP).
.PP
.SH OPTIONS
.IP "\fB\--wget\fP"
Use wget only for downloading distant files. By default curl is used if
available, or wget instead.
.IP "\fB\--curl\fP"
Use curl only for downloading distant files. By default curl is used if
available, or wget instead.
.IP "\fB\--limit-rate \fIrate\fP"
Try to limit the download speed, \fIrate\fP is given in bytes/sec. This option is
not active by default.
.IP "\fB\--proxy\fP \fIproxyhost[:port|1080]\fP"
Use specified HTTP proxy.
.IP "\fB\--proxy-user\fP \fIuser:password\fP"
Use specified user and password to use for proxy authentication.
Specifying \fB\--proxy-user=ask\fP will cause urpmi.addmedia to prompt for a
username and a password.
.IP "\fB\--update\fP"
Add a medium which will be taken into account by \fBMandrivaUpdate\fP or
by \fBurpmi --update\fP when looking for updates.
.IP "\fB\--probe-synthesis\fP"
Try to find and use synthesis file if \fBwith ...\fP is not given.
.IP "\fB\--probe-hdlist\fP"
Try to find and use hdlist file if \fBwith ...\fP is not given.
.IP "\fB\--no-probe\fP"
Do not try to find any synthesis or hdlist file.
.IP "\fB\--distrib\fP"
Retrieve a set of media from a distribution. Typically, the URL provided to
\fBurpmi.addmedia\fP will represent the parent directory of a directory
\fBmedia\fP, which in turn will contain various subdirectories for each medium
of the distribution. <\fIname\fP> is combined with medium names found to create
newer medium names in the urpmi database. The \fBwith ...\fP option, if
provided, is ignored, as hdlists found on the installation medium are used
instead automatically.
.IP "\fB\--from\fP \fIurl\fP"
Use specified URL for list of mirrors. The default is
taken from the file /etc/urpmi/mirror.config, or
\fIhttp://www.mandrivalinux.com/mirrorsfull.list\fP if this file doesn't
exist.
.IP "\fB\--version\fP \fIversion\fP"
Use specified distribution version. The default is taken from the version of
the distribution told by the installed mandriva-release package.
.IP "\fB\--virtual\fP"
Create a virtual medium, this only works for file:// and removable:// protocol
and no files will be created in /var/lib/urpmi. The medium is always up-to-date
and so it does not need to be updated by \fBurpmi.update\fP.
.IP "\fB\--norebuild\fP"
Don't try to rebuild the hdlist files from the RPMs if the original hdlist wasn't
readable or was corrupted.
.IP "\fB\--raw\fP"
Add the new media in the urpmi configuration file, but don't update it nor
proceed to any download. The media, to be usable, will need to be updated with
\fBurpmi.update\fP.
.IP "\fB\--nopubkey\fP"
Don't import pubkey of added media
.IP "\fB\-c\fP"
Clean headers cache directory in /var/cache/urpmi/headers.
.IP "\fB\-h\fP"
Try to find and use synthesis or hdlist file.
.IP "\fB\-f\fP"
Force rebuild of base files, or of hdlist files when specified twice.
.SH VARIABLES
Beginning with urpmi 4.6.16, you can use variables in media URLs
(for example \fB/mnt/mirror/$RELEASE/$ARCH/media/main\fP). The variables
supported so far are:
.IP "\fB$ARCH\fP"
The architecture (as given in /etc/mandriva-release)
.IP "\fB$RELEASE\fP"
The OS release (as given in /etc/mandriva-release; its value is
\fBcooker\fP on a cooker system.)
.IP "\fB$HOST\fP"
The canonical hostname of the machine urpmi runs on.
.SH FILES
See \fIurpmi.files\fP(5).
.SH "SEE ALSO"
\fIurpmi\fP(8),
\fIurpmi.update\fP(8),
\fIurpmi.removemedia\fP(8),
\fIurpmf\fP(8),
\fIurpmq\fP(8),
\fIurpmi.files\fP(5).
.SH AUTHOR
Pascal Rigaux (original author),
Francois Pons,
Rafael Garcia-Suarez, <rgarciasuarez@mandriva.com>
(current maintainer)
