.TH urpmi.update 8 "28 Aug 2003" "Mandrakesoft" "Mandrakelinux"
.IX urpmi.update
.SH NAME
urpmi.update \- Updates package lists for specified media
.SH SYNOPSIS
.B urpmi.update [options] [<\fInames\fP>]
.SH DESCRIPTION
urpmi.update scans the specified urpmi media to update their package list.
.PP
<\fInames\fP> is a list of names you first told to urpmi.addmedia.

.SH OPTIONS
.IP "\fB\--wget\fP"
Use wget only for downloading distant files. By default curl is used if
available, or wget instead.
.IP "\fB\--curl\fP"
Use curl only for downloading distant files. By default curl is used if
available, or wget instead.
.IP "\fB\--limit-rate \fIrate\fP"
Try to limit the download speed, \fIrate\fP is given in bytes/sec. This option is
not active by default.
.IP "\fB\--proxy\fP \fIproxyhost[:port|1080]\fP"
Use specified HTTP proxy.
.IP "\fB\--proxy-user\fP \fIuser:password\fP"
Use specified user and password to use for proxy authentication.
.IP "\fB\--update\fP"
Use only update media.
.IP "\fB\--no-md5sum\fP"
Disable MD5SUM file checking.
.IP "\fB\--force-key\fP"
Force update of GPG key.
.IP "\fB\--norebuild\fP"
Don't try to rebuild the hdlist files from the RPMs if the original hdlist wasn't
readable or was corrupted.
.IP "\fB\-a\fP"
Select all media that are not using a removable device to update them.
.IP "\fB\-c\fP"
Clean /var/cache/urpmi/headers directory on exit.
.IP "\fB\-f\fP"
Force rebuild of base files, or of hdlist files when specified twice.
.IP "\fB\-q\fP"
Quiet mode.
.IP "\fB\-v\fP"
Verbose mode.
.SH FILES
See \fIurpmi.files\fP(5).
.SH "SEE ALSO"
\fIurpmi\fP(8),
\fIurpmi.addmedia\fP(8),
\fIurpmi.removemedia\fP(8),
\fIurpmf\fP(8),
\fIurpmq\fP(8),
\fIurpmi.files\fP(5).
.SH AUTHOR
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com> (original author)
.PP
Francois Pons, Mandrakesoft <fpons@mandrakesoft.com>
.PP
Rafael Garcia-Suarez, Mandrakesoft <rgarciasuarez@mandrakesoft.com>
(current maintainer)
