.TH urpmi.addmedia 8 "29 Aug 2002" "MandrakeSoft" "Mandrake Linux"
.IX urpmi.addmedia
.SH NAME
urpmi.addmedia \- adds a new rpms media for use with urpmi
.SH SYNOPSIS
.B urpmi.addmedia [\fIoptions\fP] <\fIname\fP> <\fIurl\fP>
.SH DESCRIPTION
urpmi.addmedia tells urpmi that he can find new rpms at the specified
location. Currently supported medias are: local drives, removable drives
(such as cd's), http and ftp.
.PP
One of the following modes must be choosen:
.PP
http:
.br
.IP "\fB urpmi.addmedia [\fIoptions\fP] <\fIname\fP> http://<\fIhost\fP>/<\fIpath\fP> [with <\fIrelative path of synthesis|hdlist\fP>]\fP"
Where <\fIname\fP> is your reference for the media (e.g. MandrakeUpdate).
<\fIname\fP> is optional if \fB--distrib\fP is given in \fIoptions\fP.
.br
<\fIhost\fP>/<\fIpath\fP> is the location of the rpm directory on the net.
.br
<\fIrelative path of hdlist\fP> is the pathname where to find the hdlist of
the rpms. The location is given relative to <\fIpath\fP>.
.br
\fBcurl\fP is used by default to download files, \fBwget\fP may be used if
\fBcurl\fP is not installed or \fB--curl\fP is given in \fIoptions\fP.
.PP
ftp:
.IP "\fB urpmi.addmedia [\fIoptions\fP] <\fIname\fP> ftp://<\fIlogin\fP>:<\fIuser\fP>@ <\fIhost\fP>/<\fIpath\fP> [with <\fIrelative path of synthesis|hdlist\fP>]\fP"
The same as for http, just add your login and user if required (Note that
you needn't to specify anonymous as login for anonymous access ftp servers).
.br
Note that if \fBwget\fP is used to download files with a firewall you may
have to add \fBpassive_ftp=on\fP option to \fB/etc/wgetrc\fP. 
.nf
eg: urpmi.addmedia ftp ftp://a:a@leia//export/Mandrake/RPMS with ../base/hdlist
.fi
.PP
Local drive or NFS:
.br
.IP "\fB urpmi.addmedia [\fIoptions\fP] <\fIname\fP> file://<\fIpath\fP>\fP [with <\fIrelative path of hdlist\fP>]\fP"
Where <\fIname\fP> is your reference for the media (e.g. Myrpms).
.br
<\fIpath\fP> is the location of the rpm directory on your machine.
.PP
Removable device:
.br
.IP "\fB urpmi.addmedia [\fIoptions\fP] <\fIname\fP> removable://<\fIpath\fP>\fP [with <\fIrelative path of hdlist\fP>]\fP"
<\fIpath\fP> is the location of the rpm directory on your machine when the
removable device is mounted.
.PP
.SH OPTIONS
.IP "\fB\--wget\fP"
use wget only for downloading distant files. By default curl is used if
available or wget instead.
.IP "\fB\--curl\fP"
use curl only for downloading distant files. By default curl is used if
available or wget instead.
.IP "\fB\--update\fP"
add a medium which will be taken into account when updating only update media by
\fBurpmi\fP.
.IP "\fB\--distrib\fP"
add all media from an installation medium. <\fIname\fP> if used is used with
medium name found to create newer medium name in urpmi database. The \fBwith
[...]\fP is not used as hdlist found on installation medium are used
automatically.
.SH FILES
/usr/sbin/urpmi.addmedia
.br
The \fBurpmi.addmedia\fP executable (perl script)
.PP
/var/lib/urpmi/list.*
.br
Contains the list of all packages known by urpmi and their location. There
is one filelist per media(*).
.PP
/var/lib/urpmi/hdlist.*
.br
Contain information about all known packages, it's a summary of rpm headers.
There is one filelist per media(*).
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Contain synthesis information about all known packages built from hdlist files
that can be used by minimal closure algorithm. If these files are not present
use \fBurpmi.update -a\fP to generate them. These files are not mandatory.
.PP
/etc/urpmi/urpmi.cfg
.br
Contains media description, previous format from older urpmi is accepted.
.PP
/etc/urpmi/parallel.cfg
.br
Contains parallel alias description, format is
\fB<alias>:<interface[(media)]>:<interface_parameter>\fP where \fB<alias>\fP is
a symbolic name, \fB<interface>\fP can be \fBka-run\fP or \fBssh\fP,
\fB<media>\fP is a media list (as \fB--media\fP parameter),
\fB<interface_parameter>\fP is a specific interface parameter list like "-c ssh
-m node1 -m node2" for \fBka-run\fP extension or "node1:node2" for \fBssh\fP
extension.
.PP
/etc/urpmi/skip.list
.br
Contains package expressions that should not be automatically updated. The
format is a list of provide of package (or regular expression if bounded by
slashes (\fB/\fP)) with optional operator and version string, or regular
expression to match the fullname of packages too.
.PP
/etc/urpmi/inst.list
.br
Contains package names that should be installed instead of updated.
.SH "SEE ALSO"
urpmi(8),
urpmi.update(8),
urpmi.removemedia(8),
autoirpm(8),
autoirpm-icons(8),
gurpmi(8),
urpmf(8),
urpmq(8),
rpmdrake(8)
.SH AUTHOR
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com>
.br
Francois Pons, Mandrakesoft <fpons@mandrakesoft.com>
