.TH urpmi 8 "12 Feb 2002" "MandrakeSoft" "Mandrake Linux"
.IX urpmi
.SH NAME
urpmi \- rpm wrapper making installs easier for the user
.SH SYNOPSIS
.B urpmi [\fIoptions\fP] [\fIpackage_names\fP | \fIrpm_files...\fP]
.SH DESCRIPTION
urpmi authorizes well-known rpms (or rpm files) to be installed including
all their dependencies.
You can use it to install source package dependencies too as root, or source
package itself as simple user.

You can compare rpm vs. urpmi  with  insmod vs. modprobe or dpkg vs apt-get
.PP
Just launch urpmi followed by what you think is the name of the package(s),
and urpmi will:
.br
\- Propose different package names if availables and quit.
.br
\- If only one corresponding package is found, check whether dependencies are 
already installed, or not.
.br
\- If not, propose to install the dependencies and then install all required
dependencies and the package.
.PP
Note that urpmi handle installations from various medias (ftp, http, local and
nfs volumes, removable medias such as CDROMs) and is able to install
dependencies from a media different from the package's media.
If necessary, urpmi asks you to insert the required media.
.PP
To add a new media containing rpms run urpmi.addmedia.
.br
To remove a media use urpmi.removemedia.
.br
To update the packages list (for example when the ftp archive changed) use
urpmi.update.
.br
To automatically install a package corresponding to an executable you tried
to launch, use autoirpm.
.br
To install all available menu entries of all known packages,
use autoirpm-icons.
.SH OPTIONS
.IP "\fB\--help\fP"
print an help message and exit (this is the same as \fB-h\fP or \fB-?\fP).
.IP "\fB\--update\fP"
use only update media. This means \fBurpmi\fP will search and resolve
dependencies only in media marked as update.
.IP "\fB\--media\fP"
select specific media to use instead of all media available (or update media is
\fB--update\fP is used).
.IP "\fB\--auto\fP"
installs all required dependencies without asking.
.IP "\fB\--auto-select\fP"
automatically select all packages that have to be upgraded according to already
installed packages and packages listed in various media registered.
.IP "\fB\--fuzzy\fP"
disable fast search on exact package name, ie it will propose all
package containing the name even if one has the given name (this is the same
as \fB\-y\fP).
.IP "\fB\--src\fP"
next package name is a source package and it will select all dependencies if
\fBurpmi\fP is run as root or only install source package as simple user (this
is the same as \fB\-s\fP).
.IP "\fB\--noclean\fP"
do not remove any package from the cache (/var/cache/urpmi/rpms).
.IP "\fB\--complete\fP"
use parsehdlist server to complete \fB--auto-select\fP selection (should not be
necessary in most cases).
.IP "\fB\--force\fP"
assumes yes on all questions.
.IP "\fB\--wget\fP"
use wget only for downloading distant files. By default curl is used if
available or wget instead.
.IP "\fB\--curl\fP"
use curl only for downloading distant files. By default curl is used if
available or wget instead.
.IP "\fB\--X\fP"
use X interface.
.IP "\fB\--best-output\fP"
try to use X interface or if not available the standard text interface (using
rpm).
.IP "\fB\-a\fP"
if multiple packages match the substring given, take them all
.IP "\fB\-p\fP"
allow search in provides to find package (default).
.IP "\fB\-P\fP"
do not search in provides to find package (this is the opposite of \fB-p\fP).
.IP "\fB\-y\fP"
this is the same as \fB--fuzzy\fP.
.IP "\fB\-s\fP"
this is the same as \fB--src\fP.
.IP "\fB\-q\fP"
proposes a quiet mode when calling rpm where no upgrade status are printed.
.IP "\fB\-v\fP"
proposes a verbose mode with various messages.
.SH FILES
/usr/sbin/urpmi
.br
The \fBurpmi\fP executable (perl script)
.PP
/var/lib/urpmi/list.*
.br
Contains the list of all packages known by urpmi and their location.
There is one filelist per media(*).
.PP
/var/lib/urpmi/hdlist.*
.br
Contains information about all known packages, it's a summary of rpm headers.
There is one hdlist per media(*).
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Contains synthesis information about all known packages built from hdlist files
that can be used by minimal closure algorithm. If these files are not present
use \fBurpmi.update -a\fP to generate them.
.PP
/etc/urpmi/urpmi.cfg
.br
Contains media description, previous format from older urpmi is accepted.
.PP
/etc/urpmi/skip.list
.br
Contains package names that should be not automatically updated.
.PP
/etc/urpmi/inst.list
.br
Contains package names that should be installed instead of updated.
.SH "SEE ALSO"
urpmi.addmedia(8),
urpmi.update(8),
urpmi.removemedia(8),
autoirpm(8),
gurpmi(8),
urpmf(8),
urpmq(8),
rpmdrake(8)
.SH AUTHOR
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com>
.br
Francois Pons, Mandrakesoft <fpons@mandrakesoft.com>
