.TH urpmi.removemedia 8 "07 Jan 2003" "Mandriva" "Mandriva Linux"
.IX urpmi.removemedia
.SH NAME
urpmi.removemedia \- remove a rpm media from the known media of urpmi
.SH SYNOPSIS
.B urpmi.removemedia [options] <\fInames\fP>
.SH DESCRIPTION
urpmi.removemedia removes from all configuration files all references to
the named media and to rpms from that media.
.PP
<\fInames\fP> is a list of names you first told to urpmi.addmedia.

.SH OPTIONS
.IP "\fB\-a\fP"
Select and remove all media.
.IP "\fB\-c\fP"
Clean header cache directory (/var/cache/urpmi/headers).
.SH FILES
See \fIurpmi.files\fP(5).
.SH "SEE ALSO"
\fIurpmi\fP(8),
\fIurpmi.addmedia\fP(8),
\fIurpmi.update\fP(8),
\fIurpmf\fP(8),
\fIurpmq\fP(8),
.SH AUTHOR
Pascal Rigaux (original author),
Francois Pons,
Rafael Garcia-Suarez, <rgarciasuarez@mandriva.com>
(current maintainer)
