.TH urpmi 8 "12 Oct 2005" "Mandriva" "Mandriva Linux"
.IX urpmi
.SH NAME
urpmi \- rpm downloader, installer and dependency solver
.SH SYNOPSIS
.B urpmi [\fIoptions\fP] [\fIpackage_names\fP | \fIrpm_files...\fP]
.SH DESCRIPTION
urpmi authorizes well-known rpms (or rpm files) to be installed including
all their dependencies.
You can use it to install the dependencies of a source package, or a source
package itself.

You can compare rpm vs. urpmi with insmod vs. modprobe or dpkg vs apt-get.
.PP
Just launch urpmi followed by what you think is the name of the package(s),
and urpmi will:
.br
\- Propose different package names if the name was ambiguous, and quit.
.br
\- If only one corresponding package is found, check whether its dependencies
are already installed.
.br
\- If not, propose to install the dependencies, and on a positive answer,
proceed.
.PP
Note that urpmi handles installations from various types of media (ftp, http,
rsync, local and nfs volumes, and removable media such as CDROMs) and is able
to install dependencies from a medium different from the original package's
media. For removable media, urpmi may ask you to insert the appropriate disk,
if necessary.
.PP
To add a new medium containing rpms, run urpmi.addmedia.
.br
To remove an existing medium, use urpmi.removemedia.
.br
To update the package list (for example when the ftp archive changes) use
urpmi.update.
.SH OPTIONS
.IP "\fB\--help\fP"
Print a help message and exit (this is the same as \fB-h\fP or \fB-?\fP).
.IP "\fB\--update\fP"
Use only update media. This means that \fBurpmi\fP will search packages and
resolve dependencies only in media marked as containing updates.
.IP "\fB\--media\fP \fImedia1,...,mediaN\fP"
Select specific media to be used, instead of defaulting to all available media (or
all update media if \fB--update\fP is used).
.IP "\fB\--excludemedia\fP \fImedia1,...,mediaN\fP"
Do not use the specified media.
.IP "\fB\--searchmedia\fP \fImedia\fP"
Use only the specified media to search for packages when combined with
\fB\--auto-select\fP.
.IP "\fB\--sortmedia\fP \fImedia1,...,mediaN\fP"
Sort the specified media. Substrings may be used to simplify grouping.
.IP "\fB\--synthesis\fP \fIfile\fP"
Use the specified synthesis file instead of the urpmi database for
searching packages and resolving dependencies.
.IP "\fB\--auto\fP"
Install all required dependencies without asking.
.IP "\fB\--auto-select\fP"
Automatically select all packages that have to be upgraded, according to already
installed packages and packages listed in various registered media.
.IP "\fB\--no-install\fP"
Only download packages, don't install them. You'll find them in
/var/cache/urpmi/rpms.
.IP "\fB\--no-uninstall\fP"
Never ask to uninstall a package but prefer aborting instead. This can be
safer in auto mode.
.IP "\fB\--keep\fP"
When some dependencies cannot be satisfied, change the selection of packages
to try to keep existing packages instead of removing them. This behaviour
generally rejects the upgrade of packages given on command line (or when using
\fB\--auto-select\fP) when a dependency error occurs.
.IP "\fB\--split-level \fInumber\fP"
Split urpmi's operation in small transactions when the total number of
packages to upgrade is greater than the given \fInumber\fP. This option is
activated by default, and the default value of \fInumber\fP is 20.
.IP "\fB\--split-length \fIcount\fP"
Split urpmi's operation in small transactions of at least \fIcount\fP
packages. The default is 1 and setting this value to 0 just disables splitting
in small transactions.
.IP "\fB\--fuzzy\fP"
Disable fast search on exact package name; that means that urpmi will propose
all packages matching the name partially, even if one of them matches exactly
the specified name (this is the same as \fB\-y\fP).
.IP "\fB\--src\fP \fIname\fP"
Search a source package matching \fIname\fP and select all its dependencies by
default, unless \fB\--install-src\fP is used in order to install the source
package itself.
.IP "\fB\--install-src\fP"
Install only the source package (no binary packages will be installed).
.IP "\fB\--clean\fP"
Remove all packages from the cache in directory /var/cache/urpmi/rpms.
.IP "\fB\--noclean\fP"
Do not remove any package from the cache in directory /var/cache/urpmi/rpms.
.IP "\fB\--force\fP"
Assume yes on all questions.
.IP "\fB\--allow-nodeps\fP"
With this option, urpmi will ask the user on error whether it should continue
the installation without checking dependencies. By default, urpmi exits
immediately in this case.
.IP "\fB\--allow-force\fP"
With this option, urpmi will ask the user on error whether it should proceed
to a forced installation. By default, urpmi exits immediately in this case.
.IP "\fB\--parallel\fP \fIalias\fP"
Activate distributed execution of urpmi to other machines (it is mandatory that
urpmi is installed, but it is not necessary to have media defined on any
machines). \fIalias\fP defines which extension module is to be used by urpmi
(currently, \fBurpmi-parallel-ka-run\fP or \fBurpmi-parallel-ssh\fP are
available) and which machines should be updated. This alias is defined in the
file /etc/urpmi/parallel.cfg as described below.
.IP "\fB\--root\fP \fIdirectory\fP"
Use the file system tree rooted for rpm install. All operations and scripts
will run after chroot(2). The rpm database that lies in the rooted tree will
be used, but the urpmi configuration comes from the normal system.
.IP "\fB\--use-distrib\fP \fIdirectory\fP"
Configure urpmi on the fly from a distrib tree, useful to install a chroot with
the \fB--root\fP option.
.IP "\fB\--wget\fP"
Use wget for downloading distant files. By default curl is used if
available, or wget instead.
.IP "\fB\--curl\fP"
Use curl for downloading distant files. By default curl is used if
available, or wget instead.
.IP "\fB\--limit-rate \fIrate\fP"
Try to limit the download speed, \fIrate\fP is given in bytes/sec. This option is
not active by default.
.IP "\fB\--resume\fP"
Resume transfer of partially-downloaded files.
.IP "\fB\--retry\fP \fItimes\fP"
Retries to download files over FTP or HTTP the specified number of times.
.IP "\fB\--proxy\fP \fIproxyhost[:port|1080]\fP"
Use specified HTTP proxy.
.IP "\fB\--proxy-user\fP \fIuser:password\fP"
Use specified user and password to use for proxy authentication.
Specifying \fB\--proxy-user=ask\fP will cause urpmi to prompt for a username
and a password.
.IP "\fB\--bug\fP \fIdirectory\fP"
Create a bug report in \fIdirectory\fP. You have to send a compressed archive of
the directory to the urpmi maintainer for the bug being (probably)
reproduced.
.IP "\fB\--env\fP \fIdirectory\fP"
Use a different environment directly from a bug report to replay a bug. The
argument is the same argument given to \fB--bug\fP option.
.IP "\fB\--verify-rpm\fP"
.IP "\fB\--no-verify-rpm\fP"
Activate or deactivate rpm signature checking. It's activated by default.
.IP "\fB\--test\fP"
Test (same as \fBrpm --test\fP) installation of packages but do not modify the
system.
.IP "\fB\--excludepath\fP \fIstring\fP"
Do not install files of which the names begin with the given \fIstring\fP (same
as \fBrpm --excludepath\fP).
.IP "\fB\--excludedocs\fP"
Do not install documents files (same as \fBrpm --excludedocs\fP).
.IP "\fB\--ignoresize\fP"
Don't check file systems for sufficient disk space before installation. This
is equivalent to \fBrpm --ignoresize\fP.
.IP "\fB\--skip\fP \fIpattern,...\fP"
You can specify a list of packages which installation should be skipped. You
can also include patterns between //, just like in /etc/urpmi/skip.list (see
\fIurpmi.files\fP(5)).
.IP "\fB\--more-choices\fP"
When several packages are found, propose more choices than the default.
.IP "\fB\--norebuild\fP"
Don't try to rebuild the hdlist files from the RPMs if the original hdlist wasn't
readable or was corrupted.
.IP "\fB\--strict-arch\fP"
Upgrade only packages if the newer version has the same architecture as the
one installed. Mostly useful on machines that support several architectures
(32 and 64 bit).
.IP "\fB\-a\fP"
If multiple packages match the given substring, install them all.
.IP "\fB\-p\fP"
Allow search in provides to find package (default).
.IP "\fB\-P\fP"
Do not search in provides to find package (this is the opposite of \fB-p\fP).
.IP "\fB\-y\fP"
This is the same as \fB--fuzzy\fP.
.IP "\fB\-s\fP"
This is the same as \fB--src\fP.
.IP "\fB\-q\fP"
Quiet mode: when calling rpm no upgrade status is printed.
.IP "\fB\-v\fP"
Proposes a verbose mode with various messages.
.SH EXAMPLES
.IP "urpmi ssh://foo@bar.net/home/foo/test.rpm"
Fetch /home/foo/test.rpm from server bar.net over ssh using user foo.
You can use a public key or enter your password.

.IP "urpmi --media foo- --auto-select"
Fetch all the updates from media containing foo- in their name.

.SH FILES
See \fIurpmi.files\fP(5).
.SH EXIT CODES
.IP 1
Command line inconsistency.
.IP 2
Problem registering local packages.
.IP 3
Source packages not retrievable.
.IP 4
Medium is not selected.
.IP 5
Medium already exists.
.IP 6
Unable to save configuration.
.IP 7
Urpmi database locked.
.IP 8
Unable to create bug report.
.IP 9
Unable to open rpmdb.
.IP 10
Some files are missing for installation.
.IP 11
Some transactions failed but not all.
.IP 12
All transactions failed.
.IP 13
Some files are missing and some transactions failed but not all.
.IP 14
Some files are missing and all transactions failed.
.SH "BUG REPORTS"
If you find a bug in \fBurpmi\fP please report it using
.I urpmi --bug bug_name_as_directory ...
command with the command line used, it will automatically create a directory
called \fIbug_name_as_directory\fP containing necessary files to reproduce it if
possible.
.PP
Please test the report using
.I urpmi --env bug_name_as_directory ...
to check that the bug is still here. Obviously, only reproducible bugs can be
resolved.
.PP
For sending the report, use
.I tar cvfz bug_name_as_directory.tgz bug_name_as_directory
and send it directly to the current maintainer
with a description of what you think is wrong.
.SH BUGS
When a package is removed, it may not be replaced with an older version.
.SH AUTHOR
Pascal Rigaux (original author), Francois Pons,
Rafael Garcia-Suarez, <rgarciasuarez@mandriva.com>
(current maintainer)
.SH CONTRIBUTORS
Please mail to authors if you are not belonging to this alphabetically sorted
list after having contributed.
.PP
Andrej Borsenkow,
Guillaume Cottenceau,
Philippe Libat,
Bryan Paxton,
Guillaume Rousse,
Michael Scherer,
Alexander Skwar,
Olivier Thauvin,
Erwan Velu,
Florent Villard.
.SH SEE ALSO
\fIurpmi.addmedia\fP(8),
\fIurpmi.update\fP(8),
\fIurpmi.removemedia\fP(8),
\fIurpmf\fP(8),
\fIurpmq\fP(8),
\fIurpmi.cfg\fP(5),
\fIurpmi.files\fP(5).
