.TH urpmf 8 "12 Sep 2005" "Mandriva" "Mandriva Linux"
.IX urpmf
.SH NAME
urpmf \- Finds the packages matching some conditions
.SH SYNOPSIS
.B urpmf [\fIoptions\fP] <\fIpattern\fP>
.SH DESCRIPTION
By default, urpmf outputs a list of packages providing the file specified as an
argument on the command-line.
.PP
<\fIpattern\fP> is the name or part of the name of the file you want to locate.
Perl-style regular expressions are allowed. \fBurpmf\fP will then print a list
of matching files, with their corresponding packages. By using options, you may
format output differently, and search through other rpm tags.
.PP
Note that \fBurpmf\fP searches through the urpmi media (\fBnot\fP in the
system's rpm database).
.SH OPTIONS
.IP "\fB\--help\fP"
Prints a help message and exit.
.IP "\fB\--all\fP"
Prints and searches through all parameters listed below.
.IP "\fB\--buildhost\fP"
Prints and searches through the BuildHost tag.
.IP "\fB\--conflicts\fP"
Prints and searches through the Conflicts tags.
.IP "\fB\--description\fP"
Prints and searches through the Description tag.
.IP "\fB\--env\fP \fIdirectory\fP"
Use a different environment directly from a bug report to replay a bug.
.IP "\fB\--epoch\fP"
Prints and searches through the Epoch tag.
.IP "\fB\--excludemedia\fP \fImedium1,...,mediumN\fP"
Do not use the given media.
.IP "\fB\--files\fP"
Prints and searches through the list of files contained in the rpm (this is the
default).
.IP "\fB\--group\fP"
Prints and searches through the Group tag.
.IP "\fB\--literal\fP"
Match literally instead of interpreting the argument as a regular expression.
.IP "\fB\--media\fP \fImedium1,...,mediumN\fP"
Select specific media to be used, instead of defaulting to all available media
(or all update media if \fB--update\fP is used).
.IP "\fB\--name\fP"
Prints and searches through package names.
.IP "\fB\--obsoletes\fP"
Prints and searches through the Obsoletes tags.
.IP "\fB\--packager\fP"
Prints and searches through the Packager tag.
.IP "\fB\--provides\fP"
Prints and searches through the Provides tags.
.IP "\fB\--quiet\fP"
Do not print tag name (default if no tag given on command line, incompatible
with interactive mode).
.IP "\fB\--requires\fP"
Prints and searches through the Requires tag.
.IP "\fB\--size\fP"
Prints and searches through the Size tag.
.IP "\fB\--sortmedia\fP \fImedium1,...,mediumN\fP"
Sort the given media, substrings may be used to simplify grouping.
.IP "\fB\--sourcerpm\fP"
Prints and searches through the names of source rpms.
.IP "\fB\--summary\fP"
Prints and searches through the Summary tag.
.IP "\fB\--synthesis\fP \fIfile\fP"
Use the given synthesis file instead of urpmi db for searching packages and
resolving dependencies.
.IP "\fB\--uniq\fP"
Do not print identical lines.
.IP "\fB\--update\fP"
Use only update media. This means \fBurpmi\fP will search and resolve
dependencies only in media marked as update.
.IP "\fB\--url\fP"
Prints and searches through url.
.IP "\fB\--verbose\fP"
Verbose mode. urpmf will emit various messages related to the parsing of hdlist
files for your media.
.IP "\fB-i\fP"
Ignore case distinctions in any patterns.
.IP "\fB-q\fP"
Synonym of \fB--quiet\fP.
.IP "\fB-f\fP"
Print version, release and arch along with name of package.
.IP "\fB-m\fP"
Print the name of the media in which the package has been found.
.IP "\fB-e\fP"
Include code directly in the perl search expression. Use it with
\fB--verbose\fP to look at the generated perl code. In any cases, use it only
if you know perl.
.IP "\fB-a\fP"
Binary AND operator, true if both expressions are true.
.IP "\fB-o\fP"
Binary OR operator, true if one expression is true.
.IP "\fB-!\fP"
Unary NOT, true if expression is false.
.IP "\fB-(\fP"
Left parenthesis to open a group expression.
.IP "\fB-)\fP"
Right parenthesis to close a group expression.
.SH FILES
See \fIurpmi.files\fP(5).
.SH "SEE ALSO"
\fIurpmi.addmedia\fP(8),
\fIurpmi.update\fP(8),
\fIurpmi.removemedia\fP(8),
\fIurpmi\fP(8),
\fIurpmq\fP(8),
\fIurpmi.files\fP(5).
.SH AUTHOR
Pascal Rigaux (original author)
.PP
Francois Pons
.PP
Rafael Garcia-Suarez <rgarciasuarez@mandriva.com>
(current maintainer)
