.TH urpmf 8 "10 Sep 2003" "MandrakeSoft" "Mandrake Linux"
.IX urpmf
.SH NAME
urpmf \- RPMFind - Finds the RPM package providing specified files
.SH SYNOPSIS
.B urpmf [\fIoptions\fP] <\fIpattern\fP>
.SH DESCRIPTION
urpmf outputs a list of packages providing the file specified as an argument.
.PP
\fIpattern\fP is the name or part of the name of the file you wish to know which
packages are providing it. \fBurpmf\fP will then print a list of matching files
with their corresponding packages.
.PP
Using options you may search though other packages parameters.
\fBurpmf\fP searches through installed and uninstalled packages.
.SH OPTIONS
.IP "\fB\--help\fP"
print a help message and exit.
.IP "\fB\--update\fP"
Use only update media. This means \fBurpmi\fP will search and resolve
dependencies only in media marked as update.
.IP "\fB\--media\fP \fImedium1,...,mediumN\fP"
Select specific media to use instead of all media available (or update media is
\fB--update\fP is used).
.IP "\fB\--excludemedia\fP \fImedium1,...,mediumN\fP"
Do not use the given media.
.IP "\fB\--sortmedia\fP \fImedium1,...,mediumN\fP"
Sort the given media, substrings may be used to simplify grouping.
.IP "\fB\--synthesis\fP \fIfile\fP"
Use the given synthesis\fIfile\fP instead of urpmi db for searching packages and
resolving dependencies.
.IP "\fB\--verbose\fP"
Propose a verbose mode with various messages.
.IP "\fB\--quiet\fP"
Do not print tag name (default if no tag given on command line, incompatible
with interactive mode).
.IP "\fB\--uniq\fP"
Do not print identical lines.
.IP "\fB\--all\fP"
Search through all parameters listed below.
.IP "\fB\--group\fP"
Search through group.
.IP "\fB\--size\fP"
Search through size.
.IP "\fB\--epoch\fP"
Search through epoch.
.IP "\fB\--summary\fP"
Search through summary.
.IP "\fB\--description\fP"
Search through description.
.IP "\fB\--sourcerpm\fP"
Search through source rpm.
.IP "\fB\--packager\fP"
Search through packager.
.IP "\fB\--buildhost\fP"
Search through build host.
.IP "\fB\--url\fP"
Search through url.
.IP "\fB\--provides\fP"
Search through provides.
.IP "\fB\--requires\fP"
Search through requires.
.IP "\fB\--files\fP"
Search through files, this is the default.
.IP "\fB\--conflicts\fP"
Search through conflicts.
.IP "\fB\--obsoletes\fP"
Search through obsoletes.
.IP "\fB\--env\fP \fIdirectory\fP"
Use a different environment directly from a bug report to replay a bug, the
argument is the same argument given to \fB--bug\fP option.
.IP "\fB-c\fP"
Ignore case distinctions in any patterns.
.IP "\fB-f\fP"
Print version, release and arch along with name of package.
.IP "\fB-e\fP"
Include code directly in generated perl expression. Use it with \fB--verbose\fP
to look at perl code generated. But in any cases, use it only if you know perl.
.IP "\fB-a\fP"
Binary AND operator, true if both expression are true.
.IP "\fB-o\fP"
Binary OR operator, true if one expression is true.
.IP "\fB!\fP"
Unary NOT, true if expression is false.
.IP "\fB(\fP"
Left parenthesis to open group expression.
.IP "\fB)\fP"
Right parenthesis to close group expression.
.SH FILES
.de FN
\fI\|\\$1\|\fP
..
.TP
.FN /usr/bin/urpmf
The \fBurpmf\fP executable (perl script).
.TP
.FN /var/lib/urpmi/list.*
Contains the list of all packages known by urpmi and their location. This file
is only used when a password is used to access a distant location (using a
network protocol) or when various directories are used to store the packages.
.TP
.FN /var/lib/urpmi/hdlist.*
Contains information about all known packages; it's a summary of rpm headers.
If an hdlist file is used for a medium, \fBurpmf\fP can operate completely
without accessing this medium (this is almost always the case).
.TP
.FN /var/lib/urpmi/synthesis.hdlist.*
Contains synthesis information about all known packages built from hdlist files
that can be used by minimal closure algorithm. If these files are not present
hdlist files will be used instead but this is much slower.
.TP
.FN /etc/urpmi/urpmi.cfg
Contains media description, previous format from older urpmi is still accepted.
.TP
.FN /etc/urpmi/parallel.cfg
Contains parallel alias description, format is
\fB<alias>:<interface[(media)]>:<interface_parameter>\fP where \fB<alias>\fP is
a symbolic name, \fB<interface>\fP can be \fBka-run\fP or \fBssh\fP,
\fB<media>\fP is a media list (as \fB--media\fP parameter),
\fB<interface_parameter>\fP is a specific interface parameter list like "-c ssh
-m node1 -m node2" for \fBka-run\fP extension or "node1:node2" for \fBssh\fP
extension.
.TP
.FN /etc/urpmi/skip.list
The list of packages the should not be automatically updated when using
--auto-select. It contains one package expression per line; either a package
name followed by an optional operator and version string, or a regular
expression (if bounded by slashes \fB/\fP) to match the fullname of packages
against.
.TP
.FN /etc/urpmi/inst.list
The list of packages that should be installed instead of updated. It has
the same format as the skip.list.
.SH "SEE ALSO"
\fIurpmi.addmedia\fP(8),
\fIurpmi.update\fP(8),
\fIurpmi.removemedia\fP(8),
\fIurpmi\fP(8),
\fIurpmq\fP(8),
.SH AUTHOR
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com> (original author)
.PP
Francois Pons, Mandrakesoft <fpons@mandrakesoft.com> (current author)
