.TH urpmq 8 "28 Aug 2002" "Mandrakesoft" "Mandrakelinux"
.IX urpmq
.SH NAME
urpmq \- urpmi database query tool.
.SH SYNOPSIS
.B urpmq [\fIoptions\fP] [\fIpackage_names\fP | \fIrpm_files...\fP]
.SH DESCRIPTION
urpmq is a tool to access the urpmi database. It can be used to list available
packages in the various urpmi media, or to list the full dependencies of a
package, or to list the packages that will be installed if you start urpmi.
.PP
The output of urpmq has the following format, adjusted according to the
command-line options that were used:
.IP
[group/]package_name[-version][-release][.arch]
.PP
.SH OPTIONS
.IP "\fB\--help\fP"
Print a help message and exit (this is the same as \fB-h\fP or \fB-?\fP).
.IP "\fB\--update\fP"
Use only update media. This means that \fBurpmq\fP will search and resolve
dependencies only in media marked as containing updates.
.IP "\fB\--media\fP \fImedia1,...,mediaN\fP"
Select specific media to be used, instead of all available media (or update
media if \fB--update\fP is used).
.IP "\fB\--excludemedia\fP \fImedia1,...,mediaN\fP"
Do not use the specified media.
.IP "\fB\--searchmedia\fP \fImedia\fP"
Use only the specified medium to search for packages when combined with
\fB\--auto-select\fP.
.IP "\fB\--sortmedia\fP \fImedia1,...,mediaN\fP"
Sort the specified media. Substrings may be used to simplify grouping.
.IP "\fB\--synthesis\fP \fIfile\fP"
Use the specified synthesis file instead of the urpmi database for
searching packages and resolving dependencies.
.IP "\fB\--auto-select\fP"
Automatically select all packages that have to be upgraded, according to already
installed packages and packages listed in various registered media.
.IP "\fB\--fuzzy\fP"
Disable fast search on exact package name; i.e. it will propose all
packages matching the name partially, even if one of them matches exactly the
specified name (this is the same as \fB\-y\fP).
.IP "\fB\--keep\fP"
When some dependencies cannot be satisfied, change the selection of packages
to try to keep existing packages instead of removing them. This behaviour
generally rejects the upgrade of packages given on command line (or when using
--auto-select) when a dependency error occurs.
.IP "\fB\--list\fP"
List available packages.
.IP "\fB\--list-media\fP [\fItype\fP]"
List available media. You can optionally add a type: \fBall\fP to list
all media (the default), \fBupdate\fP to list the update media, or
\fBactive\fP to list only active media.
.IP "\fB\--list-url\fP"
List available media and their URLs.
.IP "\fB\--list-nodes\fP"
List available nodes when using \fB--parallel\fP.
.IP "\fB\--list-aliases\fP"
List available parallel aliases.
.IP "\fB\--src\fP \fIname\fP"
Search a source package according to \fIname\fP and it will select all dependencies by
default, unless \fB\--install-src\fP is used in order to install source package
itself.
.IP "\fB\--headers\fP"
Extract and dump headers of selected packages to standard output.
.IP "\fB\--sources\fP"
Print source URLs (or file names) of all selected packages.
.IP "\fB\--force\fP"
Continue when requesting packages that are not available.
.IP "\fB\--parallel\fP \fIalias\fP"
Activate distributed execution of urpmi to other machines (it is mandatory that
urpmi is installed but it is not necessary to have media defined on any
machines). \fIalias\fP defines which extension module to use by urpmi (currently
\fBurpmi-parallel-ka-run\fP or \fBurpmi-parallel-ssh\fP) and which machines
should be updated, this alias is defined in the file /etc/urpmi/parallel.cfg as
described below.
.IP "\fB\--root\fP \fIdirectory\fP"
Use the file system tree rooted for rpm install. All operations and scripts
will run after chroot(2). The rpm database in the rooted tree will be used but
urpmi configuration comes from normal system.
.IP "\fB\--wget\fP"
Use wget only for downloading distant files. By default curl is used if
available or wget instead.
.IP "\fB\--curl\fP"
Use curl only for downloading distant files. By default curl is used if
available or wget instead.
.IP "\fB\--proxy\fP \fIproxyhost[:port|1080]\fP"
Use specified HTTP proxy.
.IP "\fB\--proxy-user\fP \fIuser:password\fP"
Use specified user and password to use for proxy authentication.
.IP "\fB\--env\fP \fIdirectory\fP"
Use a different environment directly from a bug report to replay a bug, the
argument is the same argument given to \fB--bug\fP option.
.IP "\fB\-v\fP"
Activate verbose mode.
.IP "\fB\-d\fP"
Select dependencies (maximal closure).
.IP "\fB\-u\fP"
Deselect packages if a better version is already installed, this option can be
used with \fB-d\fP to simulate \fB-M\fP mode of \fBurpmi\fP.
.IP "\fB\-a\fP"
Select all matches on command line, useful when using \fB-f\fP or \fB-r\fP with
incomplete name given.
.IP "\fB\-c\fP"
If maximal closure is used, assume that a package listed may have wrong or not
up-to-date dependencies. This causes more packages to be upgraded and may
correct unresolved dependencies on the rpm database.
.IP "\fB\-p\fP"
Search in provides to find package (this is the opposite of \fB-P\fP).
.IP "\fB\-P\fP"
Do not search in provides to find package (this is the opposite of \fB-p\fP and
is the default).
.IP "\fB\-R\fP"
Reverse search to what requires the package given.
.IP "\fB\-y\fP"
This is the same as \fB--fuzzy\fP.
.IP "\fB\-Y\fP"
Like \fB-y\fP, but forces to match case-insensitively.
.IP "\fB\-s\fP"
This is the same as \fB--src\fP.
.IP "\fB\-i\fP"
Print useful information in human readable form, as for \fIrpm -qi\fP.
.IP "\fB\-g\fP"
Print group of each package listed.
.IP "\fB\-r\fP"
Print version and release of each package listed.
.IP "\fB\-f\fP"
Print version, release and arch of each package listed.
.SH FILES
See \fIurpmi.files\fP(5).
.SH SEE ALSO
\fIurpmi.addmedia\fP(8),
\fIurpmi.update\fP(8),
\fIurpmi.removemedia\fP(8),
\fIurpmf\fP(8),
\fIurpmi\fP(8),
\fIurpmi.files\fP(5).
.SH AUTHOR
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com> (original author)
.PP
Francois Pons, Mandrakesoft <fpons@mandrakesoft.com>
.PP
Rafael Garcia-Suarez, Mandrakesoft <rgarciasuarez@mandrakesoft.com>
(current maintainer)
