.TH urpmq 8 "08 Jan 2002" "Mandrakesoft" "Mandrakelinux"
.IX urpmq
.SH NIMI
urpmq \- urpmi tietokannan hakutyökalu.
.SH YLEISKATSAUS
.B urpmq [\fIoptiot\fP] [\fIpaketti_nimi\fP | \fIrpm_tiedosto...\fP]
.SH KUVAUS
urpmq sallii hakuja urpmi tietokannasta. Se on oikea työkalu sinulle jos haluat
listata käytettävissä olevia paketteja eri urpmin tuntemia medioistam tai listata
pakettien riippuvuuksia tai paketteja jota asennetaan jos suoritat urpmi.
.PP
urpmf tuloste on seuraava komentorivi optioiden mukaisesti:
.IP
[ryhmä/]paketti_nimi[-versio][-julkaisu][.arkitehtuuri]
.SH OPTIOT
.IP "\fB\--help\fP"
Tulostaa apuviestin ja lopettaa (tämä on sama kuuin \fB-h\fP tai \fB-?\fP).
.IP "\fB\--update\fP"
Käytä ainoastaan päivitymediaa. Tämä tarkoittaa että \fBurpmi\fP etsii ainoastaan
päivitysmedioista ja käyttää ainoastaan niitä riippuvuuksien täyttämiseksi.
.IP "\fB\--media\fP \fImedia1,...,mediaN\fP"
Valitse määrätyt mediat jota haluat käyttää, kaikkien käytettävissä olevien
medioiden sijasta (tai päivitysmediat jos \fB--update\fP on käytössä).
.IP "\fB\--synthesis\fP \fItiedosto\fP"
Käytä annettu synteesi \fItiedosto\fP urpmi tietokannan sijasta pakettien
etsinnässä ja riippuvuuksien täyttämiseksi.
.IP "\fB\--auto-select\fP"
Valitsee automaattisesti kaikki paketit jota pitää/voidaan päivittää asennettujen
pakettien mukaisesti sekä rekisteröityjen medioiden mukaisesti.
.IP "\fB\--fuzzy\fP"
Poista käytöstä pikahaku tarkalla pakettien nimillä, eli urpmi ehdottaa kaikki
paketit joiden nimet sisältävät hakemasi nimi vaikka yksi vastaa täysin hakuehtosi
(tämä on sama kuin \fB\-y\fP).
.IP "\fB\--list\fP"
Listaa käytettävissä olevia paketteja.
.IP "\fB\--list-media\fP"
Listaa käytettävissä olevia medioita.
.IP "\fB\--list-nodes\fP"
Listaa käytettävissä olevia noodeja kun käytät \fB--parallel\fP.
.IP "\fB\--list-aliases\fP"
Listaa käytettävissä olevia rinnakkaisaliakset.
.IP "\fB\--src\fP \fInimi\fP"
Etsi lähdekoodipaketti joka vastaa \fInimi\fP ja se valitsee kaikki tarvittavat
riippuvuudet oletuksena, paitsi jos \fB\--install-src\fP on käytetty kun haluat
asentaa itse lähdekoodipaketti.
.IP "\fB\--headers\fP"
Listaa valittujen pakettien otsikkotiedot näytöllä.
.IP "\fB\--sources\fP"
Listaa valittujen pakettien lähdeosoite (tai tiedosto) näytöllä.
.IP "\fB\--force\fP"
Jätä huomiotta virheilmoitukset puuttuvista haetuista paketeista.
.IP "\fB\--parallel\fP \fIalias\fP"
Ota käyttöön urpmin hajautetun suorittaminen toisille koneille (vaatii että urpmi
on asennettu niissä koneissa, mutta medioita ei tarvitse olla määritetty nissä).
\fIalias\fP märittää mikä liittymä-moduuli urpmi pitää käyttää (tällä hetkellä
\fBurpmi-parallel-ka-run\fP tai \fBurpmi-parallel-ssh\fP) ja mitkä koneet pitää
päivittää. Tämä alias (nämä aliakset) märitetään tiedostossa
/etc/urpmi/parallel.cfg (kuvattu alla).
.IP "\fB\--wget\fP"
Käytä ainoastaan wget etätiedostojen lataamisessa. Oletuksena käytetään curl
jos se on asennettu ja muuten wget.
.IP "\fB\--curl\fP"
Käytä ainoastaan curl etätiedostojen lataamisessa. Oletuksena käytetään curl
jos se on asennettu ja muuten wget.
.IP "\fB\--proxy\fP \fIvälityspalvelin[:portti|1080]\fP"
Käytä määritetty HTTP välityspalvelin.
.IP "\fB\--proxy-user\fP \fIkäyttäjä:salasana\fP"
Käytä määritetty käyttäjä ja salasana välityspalvelimen tunnistukselle.
.IP "\fB\-v\fP"
Ehdottaa yksityiskohtaisempi tila erilaisilla viestillä.
.IP "\fB\-d\fP"
Valitse riippuvuuksia (maksimaalinen päätös).
.IP "\fB\-u\fP"
Poista pakettien valinnat jos parempi versio on jo asennettu. Tämä optio
voidaan käyttää \fB-d\fP kanssa \fBurpmi\fPn \fB-M\fP tilan simulointiin.
.IP "\fB\-c\fP"
Jos maksimaalinen päätös (\fB-d\fP) on käytössä, oleta että listattujen
pakettien riippuvuudet ovat väärät tai eivät ole ajan tasalla. Tämä aiheuttaa
ettäenemmän paketteja päivitetään, ja voi korjata puuttuvia riippuvuuksia rpm
tietokannassa.
.IP "\fB\-p\fP"
Salli etsiminen "tarjoaa" tiedoista löytääksesi paketin (oletus).
.IP "\fB\-P\fP"
Älä etsi "tarjoaa" tiedoista löytääksesi paketin (tämä on \fB-p\fP vastakohta).
.IP "\fB\-y\fP"
Tämä on sama kuin \fB--fuzzy\fP.
.IP "\fB\-s\fP"
Tämä on sama kuin \fB--src\fP.
.IP "\fB\-g\fP"
Tulosta ryhmät jokaisesta  listatusta paketista.
.IP "\fB\-r\fP"
Tulosta versio ja julkaisu jokaisesta listatusta paketista.
.IP "\fB\-f\fP"
Tulosta versio, julkaisu ja arkitehtuuri jokaisesta listatusta paketista.
.SH TIEDOSTOT
.de FN
\fI\|\\$1\|\fP
..
.TP
.FN /usr/sbin/urpmq
Suoritettava \fBurpmq\fP ohjelma (perl skripti).
.TP
.FN /var/lib/urpmi/list.*
Sisältää listauksen kaikki urpmi:n tunnetuista peketeista ainoastaan jos salasanaa
on käytetty pakettien hakemisessa etäpalvelimilta (käyttäen verkko-protokolla) tai
eri hakemistoissa jotka ovat käytetty pakettien tallennukseen.
.TP
.FN /var/lib/urpmi/hdlist.*
Sisältää tietoja kaikista tunnetuista paketeista, eli yhteenveto rpm-pakettien
otsikkotiedoista. Jos hdlist-tiedosto on käytetty medialle, \fBurpmi\fP voi toimia
täydellisesti, mikä on yleensä tapana.
.TP
.FN /var/lib/urpmi/synthesis.hdlist.*
Sisältää synteesi-tiedot kaikista tunnetuista paketeista. Ne ovat luotu hdlist
tiedostoista ja voidaan käyttää pienimmillä algoritmilla. Jos näitä tiedostoja 
ei ole olemassa, hdlist-tiedostoja käytetään, mutta se on hitaampi tapa.
.TP
.FN /etc/urpmi/urpmi.cfg
Sisältää medioiden kuvaukset.
.TP
.FN /etc/urpmi/parallel.cfg
Sisältää rinnakkais-aliaksen kuvaukset, muodossa:
\fB<alias>:<liityntä[(media)]>:<liityntä_parametri>\fP jossa \fB<alias>\fP on
symbolinen nimi, \fB<liityntä>\fP voi olla \fBka-run\fP tai \fBssh\fP,
\fB<media>\fP on medialistaus (vastaa \fB--media\fP parametri),
\fB<liityntä_parametri>\fP on erityinen liityntä parametrien listaus niin kuin
"-c ssh-m node1 -m node2" jos käytät \fBka-run\fP tai "node1:node2" jos käytät
\fBssh\fP.
.TP
.FN /etc/urpmi/skip.list
sisältää lausekkeita paketeista joka ei saa päivittää automaattisesti.
Muoto on listaus pakettien 'tarjoaa' tiedoista (tai tavallinen lauseke \fB/\fP
merkkien välillä) ja optiona operaattori ja versio, tai tavallinen lauseke
joka vastaa pakettien koko nimi.
.TP
.FN /etc/urpmi/inst.list
Sisältää pakettien nimet joita pitää asentaa päivittämisen sijasta.
.SH KATSO MYÖS
\fIurpmi.addmedia\fP(8),
\fIurpmi.update\fP(8),
\fIurpmi.removemedia\fP(8),
\fIurpmf\fP(8),
\fIurpmi\fP(8),
.SH TEKIJÄT
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com> (alkuperäinen tekijä)
.PP
Francois Pons, Mandrakesoft 
.PP
Rafael Garcia-Suarez, Mandrakesoft 
