.TH urpmi.removemedia 8 "07 Jan 2003" "Mandrakesoft" "Mandrakelinux"
.IX urpmi.removemedia
.SH NIMI
urpmi.removemedia \- poista rpm tiedostojen lähdettä urpmin tunnetuista medioista
.SH YLEISKATSAUS
.B urpmi.removemedia [optiot] <\fInimet\fP>
.SH KUVAUS
urpmi.removemedia poistaa kaikki asetustiedostoista viitteitä nimettyyn
mediaan sekä siinä oleviin rpm tiedostoihin.
.PP
<\fInimet\fP> on listauksen nimistä joka olet luonut urpmi.addmedian kautta.
.SH OPTIOT
.IP "\fB\-a\fP"
Valitse kaikki mediat poistettaviksi.
.IP "\fB\-c\fP"
Tyhjennä otsikkotietojen välimuistihakemisto (/var/cache/urpmi/headers).
.SH TIEDOSTOT
.de FN
\fI\|\\$1\|\fP
..
.TP
.FN /usr/sbin/urpmi.removemedia
Suoritettava \fBurpmi.removemedia\fP ohjelma (perl skripti).
.TP
.FN /var/lib/urpmi/list.*
Sisältää listauksen kaikki urpmi:n tunnetuista peketeista ainoastaan jos salasanaa
on käytetty pakettien hakemisessa etäpalvelimilta (käyttäen verkko-protokolla) tai
eri hakemistoissa jotka ovat käytetty pakettien tallennukseen.
.TP
.FN /var/lib/urpmi/hdlist.*
Sisältää tietoja kaikista tunnetuista paketeista, eli yhteenveto rpm-pakettien
otsikkotiedoista. Jos hdlist-tiedosto on käytetty medialle, \fBurpmi\fP voi toimia
täydellisesti, mikä on yleensä tapana.
.TP
.FN /var/lib/urpmi/synthesis.hdlist.*
Sisältää synteesi-tiedot kaikista tunnetuista paketeista. Ne ovat luotu hdlist
tiedostoista ja voidaan käyttää pienimmillä algoritmilla. Jos näitä tiedostoja 
ei ole olemassa, hdlist-tiedostoja käytetään, mutta se on hitaampi tapa.
.TP
.FN /etc/urpmi/urpmi.cfg
Sisältää medioiden kuvaukset.
.TP
.FN /etc/urpmi/parallel.cfg
Sisältää rinnakkais-aliaksen kuvaukset, muodossa:
\fB<alias>:<liityntä[(media)]>:<liityntä_parametri>\fP jossa \fB<alias>\fP on
symbolinen nimi, \fB<liityntä>\fP voi olla \fBka-run\fP tai \fBssh\fP,
\fB<media>\fP on medialistaus (vastaa \fB--media\fP parametri),
\fB<liityntä_parametri>\fP on erityinen liityntä parametrien listaus niin kuin
"-c ssh-m node1 -m node2" jos käytät \fBka-run\fP tai "node1:node2" jos käytät
\fBssh\fP.
.TP
.FN /etc/urpmi/skip.list
sisältää lausekkeita paketeista joka ei saa päivittää automaattisesti.
Muoto on listaus pakettien 'tarjoaa' tiedoista (tai tavallinen lauseke \fB/\fP
merkkien välillä) ja optiona operaattori ja versio, tai tavallinen lauseke
joka vastaa pakettien koko nimi.
.TP
.FN /etc/urpmi/inst.list
Sisältää pakettien nimet joita pitää asentaa päivittämisen sijasta.
.SH KATSO MYÖS
\fIurpmi\fP(8),
\fIurpmi.addmedia\fP(8),
\fIurpmi.update\fP(8),
\fIurpmf\fP(8),
\fIurpmq\fP(8),
.SH TEKIJÄT
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com> (alkuperäinen tekijä)
.PP
Francois Pons, Mandrakesoft 
.PP
Rafael Garcia-Suarez, Mandrakesoft 
