.TH urpmi.update 8 "07 Jan 2003" "Mandrakesoft" "Mandrakelinux"
.IX urpmi.update
.SH NIMI
urpmi.update \- Päivittää määritettyjen medioiden paketti-listauksia.
.SH YLEISKATSAUS
.B urpmi.update [optiot] [<\fInimet\fP>]
.SH KUVAUS
urpmi.update tarkistaa kaikki <\fInimet\fPyt> mediat päivittääkseen niiden
pakettilistauksia. Hyödyllinen esimerkiksi ftp lähteille.
.PP
<\fInimet\fP> on listan nimistä jota olet määrittänyt urpmi.addmedian kautta.
.SH OPTIOT
.IP "\fB\--wget\fP"
Käytä ainoastaan wget etätiedostojen lataamisessa. Oletuksena käytetään curl
jos se on asennettu ja muuten wget.
.IP "\fB\--curl\fP"
Käytä ainoastaan curl etätiedostojen lataamisessa. Oletuksena käytetään curl
jos se on asennettu ja muuten wget.
.IP "\fB\--proxy\fP \fIvälityspalvelin[:portti|1080]\fP"
Käytä määritetty HTTP välityspalvelin.
.IP "\fB\--proxy-user\fP \fIkäyttäjä:salasana\fP"
Käytä määritetty käyttäjä ja salasana välityspalvelimen tunnistukselle.
.IP "\fB\-a\fP"
valitse kaikki mediat jotka eivät käytä siirrettävää mediaa päivittämiselle.
.IP "\fB\-c\fP"
Tyhjennä hakemisto /var/cache/urpmi/headers lopettaessa.
.IP "\fB\-d\fP"
Pakota täydellinen laskenta (ei enää käytössä) /var/lib/urpmi/depslist.ordered
tiedostolle.
.IP "\fB\-f\fP"
Pakota hdlist tiedostojen uudelleenluonti.
.SH TIEDOSTOT
.de FN
\fI\|\\$1\|\fP
..
.TP
.FN /usr/sbin/urpmi.update
Suoritettava \fBurpmi.update\fP ohjelma (perl skripti).
.TP
.FN /var/lib/urpmi/list.*
Sisältää listauksen kaikki urpmi:n tunnetuista peketeista ainoastaan jos salasanaa
on käytetty pakettien hakemisessa etäpalvelimilta (käyttäen verkko-protokolla) tai
eri hakemistoissa jotka ovat käytetty pakettien tallennukseen.
.TP
.FN /var/lib/urpmi/hdlist.*
Sisältää tietoja kaikista tunnetuista paketeista, eli yhteenveto rpm-pakettien
otsikkotiedoista. Jos hdlist-tiedosto on käytetty medialle, \fBurpmi\fP voi toimia
täydellisesti, mikä on yleensä tapana.
.TP
.FN /var/lib/urpmi/synthesis.hdlist.*
Sisältää synteesi-tiedot kaikista tunnetuista paketeista. Ne ovat luotu hdlist
tiedostoista ja voidaan käyttää pienimmillä algoritmilla. Jos näitä tiedostoja 
ei ole olemassa, hdlist-tiedostoja käytetään, mutta se on hitaampi tapa.
.TP
.FN /etc/urpmi/urpmi.cfg
Sisältää medioiden kuvaukset.
.TP
.FN /etc/urpmi/parallel.cfg
Sisältää rinnakkais-aliaksen kuvaukset, muodossa:
\fB<alias>:<liityntä[(media)]>:<liityntä_parametri>\fP jossa \fB<alias>\fP on
symbolinen nimi, \fB<liityntä>\fP voi olla \fBka-run\fP tai \fBssh\fP,
\fB<media>\fP on medialistaus (vastaa \fB--media\fP parametri),
\fB<liityntä_parametri>\fP on erityinen liityntä parametrien listaus niin kuin
"-c ssh-m node1 -m node2" jos käytät \fBka-run\fP tai "node1:node2" jos käytät
\fBssh\fP.
.TP
.FN /etc/urpmi/skip.list
sisältää lausekkeita paketeista joka ei saa päivittää automaattisesti.
Muoto on listaus pakettien 'tarjoaa' tiedoista (tai tavallinen lauseke \fB/\fP
merkkien välillä) ja optiona operaattori ja versio, tai tavallinen lauseke
joka vastaa pakettien koko nimi.
.TP
.FN /etc/urpmi/inst.list
Sisältää pakettien nimet joita pitää asentaa päivittämisen sijasta.
.SH KATSO MYÖS
\fIurpmi\fP(8),
\fIurpmi.addmedia\fP(8),
\fIurpmi.removemedia\fP(8),
\fIurpmf\fP(8),
\fIurpmq\fP(8),
.SH TEKIJÄT
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com> (alkuperäinen tekijä)
.PP
Francois Pons, Mandrakesoft 
.PP
Rafael Garcia-Suarez, Mandrakesoft 
