.TH urpmi.addmedia 8 "07 Jan 2003" "Mandrakesoft" "Mandrakelinux"
.IX urpmi.addmedia
.SH NIMI
urpmi.addmedia \- lisää uuden rpm median urpmin käyttöön
.SH YLEISKATSAUS
.B urpmi.addmedia [\fIoptio\fP] <\fInimi\fP> <\fIosoite\fP>
.SH KUVAUS
urpmi.addmedia kertoo urpmille mistä se voi löytää rpm-tiedostoja.
Tällä hetkellä tuetut mediat ovat: paikalliset asemat, siirrettävät asemat
(kuten cd-asemat, zip-asemat, jne.), verkkoasemia http, ftp, ssh ja rsync
protokollien kautta.
.PP
Yksi seuraavista tiloista pitää valita:
.PP
http:
.IP "\fBurpmi.addmedia [\fIoptiot\fP] <\fInimi\fP> http://<\fItunnus\fP>:<\fIsalasana\fP>@<\fIpalvelin\fP>/<\fIpolku\fP> [with <\fIrelatiivinen polku synthesis|hdlist tiedostoon\fP>]\fP"
Missä <\fInimi\fP> on sinun viitteesi medialle (esim. "updates").
<\fInimi\fP> on valinnanvarainen jos \fB--distrib\fP on annettu \fIoptio\fPna.
.br
<\fIpalvelin\fP>/<\fIpolku\fP> on rpm hakemiston sijainti internetissä.
.br
<\fIrelatiivinen polku hdlist tiedostolle\fP> on hakemisto jossa rpm tiedostoja
kuvaava hdlist tiedosto sijaitsee. Sijainti annetaan relatiivisesti <\fIpolku\fP>un
nähden.
.br
\fBcurl\fP käytetään oletuksena tiedostojen lataamiseen,\fBwget\fP käytetään jos
\fBcurl\fP ei ole asennettu tai \fB--wget\fP on annettu \fIoptio\fPna.
.br
\fIesim.\fP: urpmi.addmedia http http://jpackage.sf.net/rpm/free with hdlist.cz
.PP
ftp:
.IP "\fBurpmi.addmedia [\fIoptiot\fP] <\fInimi\fP> ftp://<\fItunnus\fP>:<\fIsalasana\fP>@<\fIpalvelin\fP>/<\fIpolku\fP> [with <\fIrelatiivinen polku synthesis|hdlist tiedostoon\fP>]\fP"
Vastaava kuin http, lisää tunnus ja salasanaa tarvittaessa (Huomaa että sinun
ei tarvitse antaa tunnusta ja salasanaa jos käytät anonyymipalvelinta).
.br
Huomaa että jos \fBwget\fP käytetään tiedostojen lataamisessa palomuurin takana
joudut ehkä lisätä \fBpassive_ftp=on\fP optiota \fB/etc/wgetrc\fP tiedostoon. 
.br
\fIesim.\fP: urpmi.addmedia ftp ftp://a:a@leia//export/media/main with ../base/hdlist.cz
.PP
ssh:
.IP "\fBurpmi.addmedia [\fIoptiot\fP] <\fInimi\fP> ssh://<\fItunnus\fP>:<\fIsalasana\fP>@<\fIpalvelin\fP>/<\fIpolku\fP> [with <\fIrelatiivinen polku synthesis|hdlist tiedostoon\fP>]\fP"
Vastaava kuin http, lisää tunnus ja salasanaa tarvittaessa. Suosittelemme
että viet 'root' avaimen tiedostolle jotta et tarvitse syöttää salasanaa
koko ajan. \fBscp\fP ja \fBrsync\fP käytetään tiedostojen hakemisessa.
.br
\fIesim.\fP: urpmi.addmedia -h ssh ssh://fpons@bi/c/i586/media/main
.PP
rsync:
.IP "\fBurpmi.addmedia [\fIoptiot\fP] <\fInimi\fP> rsync://<\fItunnus\fP>@<\fIpalvelin\fP>:<\fIportti\fP>/<\fIpolku\fP> [with <\fIrelatiivinen polku synthesis|hdlist tiedostoon\fP>]\fP"
Vastaava kuin http, voit myös käyttää <\fIpalvelin\fP>::<\fIpolku\fP>.
.br
\fIesim.\fP: urpmi.addmedia rsync rsync://ftp.orst.edu::mandrake-devel/contrib/ppc with ../../cooker/ppc/media/media_info/hdlist2.cz
.PP
Paikallinen asema tai NFS:
.br
.IP "\fB urpmi.addmedia [\fIoptiot\fP] <\fInimi\fP> file://<\fIpolku\fP>\fP [with <\fIrelatiivinen polku synthesis|hdlist tiedostoon\fP>]\fP"
Missä <\fInimi\fP> on sinun viitteesi medialle (esim. MyRPMS).
.br
<\fIpolku\fP> on rpm tiedostoja sisältävä hakemiston sijainti koneessasi.
.PP
Siirrettävät mediat:
.br
.IP "\fB urpmi.addmedia [\fIoptiot\fP] <\fInimi\fP> removable://<\fIpolku\fP>\fP [with <\fIrelatiivinen polku synthesis|hdlist tiedostoon\fP>]\fP"
<\fIpolku\fP> on rpm tiedostoja sisältävä hakemiston sijainti koneessasi
kun siirrettävä mediasi on liitetty.
.PP
.SH OPTIOT
.IP "\fB\--wget\fP"
Käytä ainoastaan wget etätiedostojen lataamisessa. Oletuksena käytetään curl
jos se on asennettu ja muuten wget.
.IP "\fB\--curl\fP"
Käytä ainoastaan curl etätiedostojen lataamisessa. Oletuksena käytetään curl
jos se on asennettu ja muuten wget.
.IP "\fB\--proxy\fP \fIvälityspalvelin[:portti|1080]\fP"
Käytä määritetty HTTP välityspalvelin.
.IP "\fB\--proxy-user\fP \fIkäyttäjä:salasana\fP"
Käytä määritetty käyttäjä ja salasana välityspalvelimen tunnistukselle.
.IP "\fB\--update\fP"
Lisää media joka huomioidaan kun halutaan käyttää ainoastaan päivitysmedioita
\fBurpmi\fPlla.
.IP "\fB\--distrib\fP"
Lisää kaikki mediat asennusmediasta. <\fInimi\fP> käytetään löydetyn median
nimen kanssa luodaakseen uudempi medianimi urpmi tietokannassa. \fBwith[...]\fP 
ei käytetä koska hdlist joka löytyy asennusmediasta käytetään automaattisesti.
.IP "\fB\--distrib-XXX\fP"
Luo automaattisesti median XXX osalle jakelusta, XXX voi olla main, contrib,
updates tai mitä vain joka on valmiiksi määritelty.
.IP "\fB\--from\fP \fIosoite\fP"
Käytä määritty \fIosoite\fP hakeaaksesi listan peilipalvelimista, oletus 
Mandrakesoft:ilta on \fIhttp://www.linux-mandrake.com/mirrorsfull.list\fP 
jos ei \fBurpmi.setup\fP on asennettu jolloin \fBurpmi.addmedia\fP etsii
sen peilipalvelinten asetustiedostoa.
.IP "\fB\--version\fP \fIversio\fP"
Käytä määritetty versio kun käytät \fB--distrib-XXX\fP, oletus on asennetun
\fBmandrake-release\fP paketin versio
.IP "\fB\--arch\fP \fIarkitehtuuri\fP"
Käytä määritetty arkitehtuuri kun käytät \fB--distrib-XXX\fP, oletus on
asennetun \fBmandrake-release\fP paketin arkitehtuuri.
.IP "\fB\-c\fP"
Tyhjennä otsikkotietojen välimuistihakemisto (/var/cache/urpmi/headers).
.IP "\fB\-h\fP"
Yrittää löytää ja käyttää synthesis tai hdlist tiedostoa.
.IP "\fB\-f\fP"
Pakota hdlist tiedostojen luominen.
.SH TIEDOSTOT
.de FN
\fI\|\\$1\|\fP
..
.TP
.FN /usr/sbin/urpmi.addmedia
Suoritettava \fBurpmi.addmedia\fP ohjelma (perl skripti).
.TP
.FN /var/lib/urpmi/list.*
Sisältää listauksen kaikki urpmi:n tunnetuista peketeista ainoastaan jos salasanaa
on käytetty pakettien hakemisessa etäpalvelimilta (käyttäen verkko-protokolla) tai
eri hakemistoissa jotka ovat käytetty pakettien tallennukseen.
.TP
.FN /var/lib/urpmi/hdlist.*
Sisältää tietoja kaikista tunnetuista paketeista, eli yhteenveto rpm-pakettien
otsikkotiedoista. Jos hdlist-tiedosto on käytetty medialle, \fBurpmi\fP voi toimia
täydellisesti, mikä on yleensä tapana.
.TP
.FN /var/lib/urpmi/synthesis.hdlist.*
Sisältää synteesi-tiedot kaikista tunnetuista paketeista. Ne ovat luotu hdlist
tiedostoista ja voidaan käyttää pienimmillä algoritmilla. Jos näitä tiedostoja 
ei ole olemassa, hdlist-tiedostoja käytetään, mutta se on hitaampi tapa.
.TP
.FN /etc/urpmi/urpmi.cfg
Sisältää medioiden kuvaukset.
.TP
.FN /etc/urpmi/parallel.cfg
Sisältää rinnakkais-aliaksen kuvaukset, muodossa:
\fB<alias>:<liityntä[(media)]>:<liityntä_parametri>\fP jossa \fB<alias>\fP on
symbolinen nimi, \fB<liityntä>\fP voi olla \fBka-run\fP tai \fBssh\fP,
\fB<media>\fP on medialistaus (vastaa \fB--media\fP parametri),
\fB<liityntä_parametri>\fP on erityinen liityntä parametrien listaus niin kuin
"-c ssh-m node1 -m node2" jos käytät \fBka-run\fP tai "node1:node2" jos käytät
\fBssh\fP.
.TP
.FN /etc/urpmi/skip.list
sisältää lausekkeita paketeista joka ei saa päivittää automaattisesti.
Muoto on listaus pakettien 'tarjoaa' tiedoista (tai tavallinen lauseke \fB/\fP
merkkien välillä) ja optiona operaattori ja versio, tai tavallinen lauseke
joka vastaa pakettien koko nimi.
.TP
.FN /etc/urpmi/inst.list
Sisältää pakettien nimet joita pitää asentaa päivittämisen sijasta.
.SH KATSO MYÖS
\fIurpmi\fP(8),
\fIurpmi.update\fP(8),
\fIurpmi.removemedia\fP(8),
\fIurpmf\fP(8),
\fIurpmq\fP(8),
.SH TEKIJÄT
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com> (alkuperäinen tekijä)
.PP
Francois Pons, Mandrakesoft 
.PP
Rafael Garcia-Suarez, Mandrakesoft 
