.TH urpmi 8 "08 Jan 2003" "Mandrakesoft" "Mandrakelinux"
.IX urpmi
.SH NIMI
urpmi \- rpm apuohjelma joka tekee asennukset helpompi käyttäjille
.SH YLEISKATSAUS
.B urpmi [\fIoptiot\fP] [\fIpakettien_nimet\fP | \fIrpm_tiedostot...\fP]
.SH KUVAUS
urpmi sallii tunnettujen rpm-tiedostojen asentaminen järjestelmään mukaanlukien
kaikki niiden riippuvuuksia. Voit käyttää sitä asentamaan paketteja ja mahdolliset
riippuvaiset paketit.
Voit verrata rpm vastaan urpmi samalla tavalla kuin insmod vastaan modprobe tai 
dpkg vastaan apt-get.
.PP
Tarvitet vain suorittaa urpmi ja sen jälkeen nimi/nimet jota luulet on olemassa
olevan/olevien paketin/pakettien nimi/nimet, ja urpmi tekee jotain näistä:
.br
\- Ehdottaa eri pakettien nimet jos olemassa ja lopettaa.
.br
\- Jos ainoastaan yksi sopiva paketti löytyy, tarkistetaan jos riippuvaiset
paketit on jo asennettu, vai ei.
.br
\- Jos ei, ehdotetaan asentamaan riippuvaiset paketit ja sitten haluamasi paketti.
.PP
Huomaa että urpmi osaa käsitellä asennuksia erilaisilta medioilta (ftp, http,
paikalliset ja nfs volyymit, siirrettävät mediat kuten cd-rom, jne) ja osaa asentaa
riippuvaiset paketit joita sijaitsevat eri mediassa kun paketti joka olet asentamassa.
Jos on tarvetta, urpmi pyytää sinua asettamaan vaadittu media.
.PP
Lisätääksesi uusi rpm tiedostoja sisältävä media käytä "\fBurpmi.addmedia\fP"
.br
Poistaaksesi median käytä "\fBurpmi.removemedia\fP"
.br
Päivittääksesi pakettien listaus (esimerkiksi kuin ftp arkisto on muuttunut) käytä
"\fBurpmi.update\fP".
.br
Käyttääksesi automaattiasennuksen joka asentaa paketteja sen mukaan mitä ohjelmaa 
yrität käyttää, käytä "\fBautoirpm\fP".
.br
Asentaaksesi kaikki käytettävissä olevia valikkotietueita kaikista tunnetuista
paketeista, käytä "\fBautoirpm-icons\fP".
.SH OPTIOT
.IP "\fB\--help\fP"
Tulostaa apuviestin ja lopettaa (tämä on sama kuuin \fB-h\fP tai \fB-?\fP).
.IP "\fB\--update\fP"
Käytä ainoastaan päivitymediaa. Tämä tarkoittaa että \fBurpmi\fP etsii ainoastaan
päivitysmedioista ja käyttää ainoastaan niitä riippuvuuksien täyttämiseksi.
.IP "\fB\--media\fP \fImedia1,...,mediaN\fP"
Valitse määrätyt mediat jota haluat käyttää, kaikkien käytettävissä olevien
medioiden sijasta (tai päivitysmediat jos \fB--update\fP on käytössä).
.IP "\fB\--synthesis\fP \fItiedosto\fP"
Käytä annettu synteesi \fItiedosto\fP urpmi tietokannan sijasta pakettien
etsinnässä ja riippuvuuksien täyttämiseksi.
.IP "\fB\--auto\fP"
Asenna kaikki tarpeelliset riippuvuudet kysymättä.
.IP "\fB\--auto-select\fP"
Valitsee automaattisesti kaikki paketit jota pitää/voidaan päivittää asennettujen
pakettien mukaisesti sekä rekisteröityjen medioiden mukaisesti.
.IP "\fB\--fuzzy\fP"
Poista käytöstä pikahaku tarkalla pakettien nimillä, eli urpmi ehdottaa kaikki
paketit joiden nimet sisältävät hakemasi nimi vaikka yksi vastaa täysin hakuehtosi
(tämä on sama kuin \fB\-y\fP).
.IP "\fB\--src\fP \fInimi\fP"
Etsi lähdekoodipaketti joka vastaa \fInimi\fP ja se valitsee kaikki tarvittavat
riippuvuudet oletuksena, paitsi jos \fB\--install-src\fP on käytetty kun haluat
asentaa itse lähdekoodipaketti.
.IP "\fB\--install-src\fP"
Asenna ainoastaan lähdekoodipaketti (binääriset paketit ei asenneta).
.IP "\fB\--clean\fP"
Poista kaikki paketit välimuistista hakemistossa /var/cache/urpmi/rpms.
.IP "\fB\--noclean\fP"
Älä poista yhtäkään paketti välimuistista hakemistossa /var/cache/urpmi/rpms.
.IP "\fB\--force\fP"
Oleta kyllä jokaiselle kysymykselle.
.IP "\fB\--allow-nodeps\fP"
Salli urpmi kysyä käyttäjältä lupaa jatkaa asennusta ilman riippuvuuksien 
tarkistusta virheen takia. Oletuksena urpmi keskeyttää asennuksen siinä tapauksessa.
.IP "\fB\--allow-force\fP"
Salli urpmi kysyä käyttäjältä lupaa jatkaa asennusta ilman riippuvuuksien 
tarkistusta tai pakkoasennuksella virheen takia. Oletuksena urpmi 
keskeyttää asennuksen siinä tapauksessa.
.IP "\fB\--parallel\fP \fIalias\fP"
Ota käyttöön urpmin hajautetun suorittaminen toisille koneille (vaatii että urpmi
on asennettu niissä koneissa, mutta medioita ei tarvitse olla määritetty nissä).
\fIalias\fP märittää mikä liittymä-moduuli urpmi pitää käyttää (tällä hetkellä
\fBurpmi-parallel-ka-run\fP tai \fBurpmi-parallel-ssh\fP) ja mitkä koneet pitää
päivittää. Tämä alias (nämä aliakset) märitetään tiedostossa
/etc/urpmi/parallel.cfg (kuvattu alla).
.IP "\fB\--wget\fP"
Käytä ainoastaan wget etätiedostojen lataamisessa. Oletuksena käytetään curl
jos se on asennettu ja muuten wget.
.IP "\fB\--curl\fP"
Käytä ainoastaan curl etätiedostojen lataamisessa. Oletuksena käytetään curl
jos se on asennettu ja muuten wget.
.IP "\fB\--proxy\fP \fIvälityspalvelin[:portti|1080]\fP"
Käytä määritetty HTTP välityspalvelin.
.IP "\fB\--proxy-user\fP \fIkäyttäjä:salasana\fP"
Käytä määritetty käyttäjä ja salasana välityspalvelimen tunnistukselle.
.IP "\fB\--bug\fP \fIhakemisto\fP"
Luo virheraportin \fIhakemisto\fPssa. Sinun pitää lähettää hakemiston sisältö
pakattuna arkistona \fBurpmi\fPn ulläpitäjälle jotta virhettä voidaan korjata.
.IP "\fB\--env\fP \fIhakemisto\fP"
Käytä eri ympäristö suoraan virhe-raportista virheen toistamiseksi.
Argumentti on sama kuin \fB--bug\fP optiota.
.IP "\fB\--X\fP"
Käytä X käyttöliittymä.
.IP "\fB\--best-output\fP"
Yritä käytä X käyttöliittymä, ja jos sitä ei ole käytettävissä käytetään
tavallinen tekstipohjainen käyttöliittymä (rpm kaltainen tuloste).
.IP "\fB\--verify-rpm\fP" tai "\fB\--no-verify-rpm\fP"
Ota käyttöön (oletus) tai poista käytöstä rpm allekirjoituksien tarkistusta.
.IP "\fB\--test\fP"
Kokeile (sama kuin \fBrpm --test\fP) pakettien asennusta, mutta varsinaista
järjestelmän muutosta ei tehdä.
.IP "\fB\--excludepath\fP"
Älä asenna tiedostoja joiden nimet alkaa annetulla hakemistolla 
(sama kuin \fBrpm --excludepath\fP).
.IP "\fB\-a\fP"
Jos monta paketteja vastaa annettu alarivi, asenna kaikki.
.IP "\fB\-p\fP"
Salli etsiminen "tarjoaa" tiedoista löytääksesi paketin (oletus).
.IP "\fB\-P\fP"
Älä etsi "tarjoaa" tiedoista löytääksesi paketin (tämä on \fB-p\fP vastakohta).
.IP "\fB\-y\fP"
Tämä on sama kuin \fB--fuzzy\fP.
.IP "\fB\-s\fP"
Tämä on sama kuin \fB--src\fP.
.IP "\fB\-q\fP"
Ehdottaa hiljaisen tilan kun kutsutaan rpm jolloin päivitystietoa ei tulosteta.
.IP "\fB\-v\fP"
Ehdottaa yksityiskohtaisempi tila erilaisilla viestillä.
.SH TIEDOSTOT
.de FN
\fI\|\\$1\|\fP
..
.TP
.FN /usr/sbin/urpmi
Suoritettava \fBurpmi\fP ohjelma (perl skripti).
.TP
.FN /var/lib/urpmi/list.*
Sisältää listauksen kaikki urpmi:n tunnetuista peketeista ainoastaan jos salasanaa
on käytetty pakettien hakemisessa etäpalvelimilta (käyttäen verkko-protokolla) tai
eri hakemistoissa jotka ovat käytetty pakettien tallennukseen.
.TP
.FN /var/lib/urpmi/hdlist.*
Sisältää tietoja kaikista tunnetuista paketeista, eli yhteenveto rpm-pakettien
otsikkotiedoista. Jos hdlist-tiedosto on käytetty medialle, \fBurpmi\fP voi toimia
täydellisesti, mikä on yleensä tapana.
.TP
.FN /var/lib/urpmi/synthesis.hdlist.*
Sisältää synteesi-tiedot kaikista tunnetuista paketeista. Ne ovat luotu hdlist
tiedostoista ja voidaan käyttää pienimmillä algoritmilla. Jos näitä tiedostoja 
ei ole olemassa, hdlist-tiedostoja käytetään, mutta se on hitaampi tapa.
.TP
.FN /etc/urpmi/urpmi.cfg
Sisältää medioiden kuvaukset.
.TP
.FN /etc/urpmi/parallel.cfg
Sisältää rinnakkais-aliaksen kuvaukset, muodossa:
\fB<alias>:<liityntä[(media)]>:<liityntä_parametri>\fP jossa \fB<alias>\fP on
symbolinen nimi, \fB<liityntä>\fP voi olla \fBka-run\fP tai \fBssh\fP,
\fB<media>\fP on medialistaus (vastaa \fB--media\fP parametri),
\fB<liityntä_parametri>\fP on erityinen liityntä parametrien listaus niin kuin
"-c ssh-m node1 -m node2" jos käytät \fBka-run\fP tai "node1:node2" jos käytät
\fBssh\fP.
.TP
.FN /etc/urpmi/skip.list
sisältää lausekkeita paketeista joka ei saa päivittää automaattisesti.
Muoto on listaus pakettien 'tarjoaa' tiedoista (tai tavallinen lauseke \fB/\fP
merkkien välillä) ja optiona operaattori ja versio, tai tavallinen lauseke
joka vastaa pakettien koko nimi.
.TP
.FN /etc/urpmi/inst.list
Sisältää pakettien nimet joita pitää asentaa päivittämisen sijasta.
.SH KATSO MYÖS
\fIurpmi.addmedia\fP(8),
\fIurpmi.update\fP(8),
\fIurpmi.removemedia\fP(8),
\fIurpmf\fP(8),
\fIurpmq\fP(8),
.SH TEKIJÄT
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com> (alkuperäinen tekijä)
.PP
Francois Pons, Mandrakesoft 
.PP
Rafael Garcia-Suarez, Mandrakesoft 

.SH VIRHEIDEN RAPORTOINTI
Jos löydät virheen \fBurpmi\fPssa, ole hyvä ja raportoi sitä käyttämällä
.I urpmi --bug virhe_nimi_hakemistona ...
komentoa komentorivissä, jolloin automaattisesti luodaan hakemisto nimellä 
\fIvirhe_nimi_hakemistona\fP joka sisältää tarvittavat tiedostot virheen
toistamiselle jos mahdollista.
.PP
Ole hyvä ja kokeile virheraporttia käyttämällä komentoa
.I urpmi --env virhe_nimi_hakemistona ...
jolla varmistat että virhe on viellä olemassa. Tällä hetkellä ainoastaan 
resoluutio-ongelmia voidaan toistaa.
.PP
Jotta voit lähettää virheraporttia, käytä komento
.I tar cvfz virhe_nimi_hakemistona.tgz virhe_nimi_hakemistona
ja lähetä luotu arkisto minulle suoraan, sekä
kirjoita viestissä mitä sinun mielessä on vikana.
.br
HUOM! Kirjoita viesti englanniksi. HUOM!
.SH VIRHEET
Kun paketti on poistettu, ei voida asentaa vanhempaa versiota sen tilalle.
.PP
Ei ole olemassa hyvää latausinikaattoria \fBwget\fPille.
