.TH urpmi.removemedia 8 "05 Jul 2001" "Mandrakesoft" "Mandrakelinux"
.IX urpmi.removemedia
.SH НАЗВА
urpmi.removemedia \- із списку відомих джерел пакунків rpm стирає
вказаний носій
.SH ВИКОРИСТАННЯ
.B urpmi.removemedia [параметри] <\fIназви\fP>
.SH ОПИС
urpmi.removemedia з усіх конфіґураційних файлів стирає всі посилання
на вказаний носій і на пакунки rpm на цьому носії.
.PP
<\fIназви\fP> \- це список назв, який ви надавали програмі urpmi.addmedia

.SH ПАРАМЕТРИ
.IP "\fB\-a\fP"
Вибрати всі носії для їх стирання.
.SH ФАЙЛИ
/usr/bin/urpmi
.br
\fBurpmi\fP виконавча програма (скрипт на мові perl)
.PP
/var/lib/urpmi/list.*
.br
Містить список всіх пакетів відомих  urpmi та їхнє місцеположення. На
кожен носій є один список файлів(*).
.PP
/var/lib/urpmi/hdlist.*
.br
Містить список всіх пакетів, це \- коротка анотація всіх заголовків rpm.
На кожен носій є один список файлів(*).
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Містить збірну інформацію про всі відомі пакети побудовані з файлів
hdlist, які можуть використовуватись алгоритмом мінімальної
відстані. Якщо таких файлів немає, скористайтесь командою
\fBurpmi.update -a\fP щоб створити їх. Ці файли необов'язкові.
.PP
/etc/urpmi/urpmi.cfg
.br
Містить описи носіїв, допускається використовувати попередній формат
від старих версій urpmi.
.PP
/etc/urpmi/skip.list
.br
Містить список тих пакетів, що  не можуть бути поновлені автоматично.
.PP
/var/lib/urpmi/depslist.ordered
.br
Простий текстовий файл, що містить всі залежності для всіх відомих пакетів.
.PP
/var/lib/urpmi/provides
.br
Простий текстовий файл, що містить опис всіх функцій  ('provides') і пакетів, які
забезпечують ту чи іншу функцію.
.PP
/var/lib/urpmi/compss
.br
Простий текстовий файл з Групами пакеті і списком пакетів для кожної групи.
this group.
.SH "ДИВ. ТАКОЖ"
urpmi(8),
urpmi.addmedia(8),
autoirpm(8),
autoirpm-icons(8),
urpmf(8),
urpmq(8),
.SH АВТОРИ
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com>
.br
Francois Pons, Mandrakesoft 
.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
