.TH urpmi.addmedia 8 "05 Jul 2001" "Mandrakesoft" "Mandrakelinux"
.IX urpmi.addmedia
.SH НАЗВА
urpmi.addmedia \- додає нові носії для використання з urpmi
.SH ВИКОРИСТАННЯ
.B urpmi.addmedia [\fIпараметри\fP] <\fIназва\fP> <\fIurl\fP>
.SH ОПИС
urpmi.addmedia повідомляє urpmi, що нові  rpms можуть бути знайденими
за вказаною адресою. На даний час підтримуються такі носії: локальні
диски, змінні диски (компакт та інші), http та ftp.
.PP
Всі користувачі, що належать до групи  urpmi можуть додавати нові
носії.
.PP
Потрібно вибрати один із наступних режимів:
.PP
http:
.br
.IP "\fB urpmi.addmedia <\fIназва\fP> http://<\fIадреса_хоста\fP>/<\fIмаршрут\fP> with <\fI відносний маршрут до  hdlist\fP>\fP"
Де <\fIназва\fP> \- це Ваша назва даного носія (наприклад: "updates").
.br
<\fIадреса хоста\fP>/<\fIмаршрут\fP> \- це розташування каталогу з rpm в тенетах.
.br
<\fIвідносний маршрут до hdlist\fP>  \- це маршрут для знаходження hdlist rpm. Положення задається відносні до <\fIмаршрут\fP>'а.
.br
Зауважте, що для отримання файлів використовується  \fBwget\fP, отже
Ви можете додати спеціальні параметри для 
\fBwget\fP відредагувавши файл  \fB/etc/wgetrc\fP. За додатковою
інформацією зверніться,  будь ласка, до документації з  \fBwget\fP.
.PP
ftp:
.br
.IP "\fB urpmi.addmedia <\fIназва\fP> ftp://<\fIім'я користувача\fP>:<\fIquser\fP>@<\fIhost\fP>/<\fIмаршрут\fP> with <\fIвідносний маршрут до hdlist\fP>\fP"
Те ж саме, що і для  http, тільки додайте ім'я користувача і пароль,
якщо це вимагається  (Не потрібно вказувати ім'я користувача і пароль
для анонімного ftp).
.br
Зауважте, що для отримання файлів використовується  \fBwget\fP, отже,
якщо Ви знаходитесь за брандмауером (firewall), Вам можливо потрібно
буде додати  \fBpassive_ftp=on\fP до \fB/etc/wgetrc\fP. 
.nf
наприклад: urpmi.addmedia ftp ftp://a:a@leia//export/media/main with ../base/hdlist
.fi
.PP
Локальний диск чи NFS:
.br
.IP "\fB    urpmi.addmedia <\fIназва\fP> file://<\fIмаршрут\fP>\fP with <\fIвідносний маршрут до hdlist\fP>\fP"
Де <\fIназва\fP> \- це Ваша назва даного носія (наприклад: Myrpms).
.br
<\fIмаршрут\fP> це знаходження каталогу з  rpm на Вашій машині.
.PP
Змінні пристрої:
.br
.IP "\fB    urpmi.addmedia removable_<\fIdevice\fP>://<\fIмаршрут\fP>\fP with <\fIвідносний маршрут до hdlist\fP>\fP"
<\fIdevice\fP> \- це назва змінного носія у вигляді, як у  /dev/ каталозі
(тобто cdrom, floppy, zip, ...).
.br
<\fIмаршрут\fP> \- це положення каталогу з rpm на машині, коли носій змонтовано.
.PP
.SH ПАРАМЕТРИ
.IP "\fB\--update\fP"
додає новий носій, який буде враховуватись при поновленні тільки
носіїв для поновлення в \fBurpmi\fP.
.SH ФАЙЛИ
/usr/bin/urpmi
.br
\fBurpmi\fP виконавча програма (скрипт на мові perl)
.PP
/var/lib/urpmi/list.*
.br
Містить список всіх пакетів відомих  urpmi та їхнє місцеположення. На
кожен носій є один список файлів(*).
.PP
/var/lib/urpmi/hdlist.*
.br
Містить список всіх пакетів, це \- коротка анотація всіх заголовків rpm.
На кожен носій є один список файлів(*).
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Містить збірну інформацію про всі відомі пакети побудовані з файлів
hdlist, які можуть використовуватись алгоритмом мінімальної
відстані. Якщо таких файлів немає, скористайтесь командою
\fBurpmi.update -a\fP щоб створити їх. Ці файли необов'язкові.
.PP
/etc/urpmi/urpmi.cfg
.br
Містить описи носіїв, допускається використовувати попередній формат
від старих версій urpmi.
.PP
/etc/urpmi/skip.list
.br
Містить список тих пакетів, що  не можуть бути поновлені автоматично.
.PP
/var/lib/urpmi/depslist.ordered
.br
Простий текстовий файл, що містить всі залежності для всіх відомих пакетів.
.PP
/var/lib/urpmi/provides
.br
Простий текстовий файл, що містить опис всіх функцій  ('provides') і пакетів, які
забезпечують ту чи іншу функцію.
.PP
/var/lib/urpmi/compss
.br
Простий текстовий файл з Групами пакеті і списком пакетів для кожної групи.
.SH "ДИВ. ТАКОЖ"
urpmi(8),
urpmi.update(8),
urpmi.removemedia(8),
autoirpm(8),
autoirpm-icons(8),
urpmf(8),
urpmq(8),
.SH АВТОРИ
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com>
.br
Francois Pons, Mandrakesoft 
.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
