.TH urpmf 8 "05 Jul 2001" "Mandrakesoft" "Mandrakelinux"
.IX urpmf
.SH НАЗВА
urpmf \- RPMFind - Шукає пакунок  RPM, який надає вказаний файл
.SH ВИКОРИСТАННЯ
.B urpmf [\fIпараметри\fP] <\fIфайл\fP>
.SH ОПИС
urpmf друкує список пакунків, які забезпечують файл вказаний, як арґумент.
.PP
<\fIфайл\fP> \- це назва файла, пакунок з яким ви хочете
відшукати. Зауважте, що Ви можете надрукувати тільки частину назви
файла, який ви шукаєте і 
\fBurpmf\fP надрукує список назв пакунків, що підходять до цього шаблона.
.PP
urpmf шукає як серед встановлених так і серед невстановлених пакунків.
.SH ПАРАМЕТРИ
.IP "\fB\--help\fP"
друкує підказку і закінчує роботу.
.IP "\fB\--quiet\fP"
не друкувати назву бирки  (стандартний режим роботи якщо бирку не
задано на командному рядку, несумісний з інтерактивним режимом роботи).
.IP "\fB\--all\fP"
друкувати всі бирки
.IP "\fB\--name\fP"
друкує бирки name: назва файла rpm (якщо не задано бирки на командному
рядку, але без назви пакунку).
.IP "\fB\--group\fP"
друкує бирку group: група
.IP "\fB\--size\fP"
друкує бирку  size: розмір
.IP "\fB\--serial\fP"
друкує бирку  serial: серійний
.IP "\fB\--summary\fP"
друкує бирку  summary: звіт
.IP "\fB\--description\fP"
друкує бирку  description: опис
.IP "\fB\--provides\fP"
друкує бирку  provides: все, що забезпечується (багато рядків).
.IP "\fB\--requires\fP"
друкує бирку  requires: все, що вимагається (багато рядків).
.IP "\fB\--files\fP"
друкує бирку  files: всі файли (багато рядків ).
.IP "\fB\--conflicts\fP"
друкує бирку  conflicts: всі конфлікти  (багато рядків).
.IP "\fB\--obsoletes\fP"
друкує бирку  obsoletes: все, що застаріло (багато рядків).
.IP "\fB\--prereqs\fP"
друкує бирку  prereqs: all prereqs (багато рядків).
.SH ФАЙЛИ
/usr/bin/urpmf
.br
Виконавчий файл \fBurpmf\fP  (скрипт на мові Perl)
/var/lib/urpmi/list.*
.br
Список всіх пакунків відомих urpmi і їхні розташування.
Для кожного носія існує окремий список. 
.PP
/var/lib/urpmi/hdlist.*
.br
Інформація про всі відомі пакунки, це \-\- звідна інформація
заголовків пакунків rpm.  Для кожного носія існує окремий список. 
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Збірна інформація про всі відомі пакунки, побудовані з файлів hdlist,
які можуть використовуватись алгоритмом найменшого набору. Якщо ці
файли не існують, скористайтесь командою  \fBurpmi.update -a\fP щоб
їх створити. Це \-\- необов'язкові файли.
.PP
/etc/urpmi/urpmi.cfg
.br
Описи носіїв, застарілий формат від старіших urpmi допускається тут.
.PP
/etc/urpmi/skip.list
.br
Містить назви пакунків, які не повинні поновлюватись автоматично.
.PP
/var/lib/urpmi/depslist.ordered
.br
Простий текстовий файл з описами всіх залежностей всіх відомих пакунків.
.PP
/var/lib/urpmi/provides
.br
Простий текстовий файл з описами всіх пакунків, властивостей наданих
ними ("provides") і зв'язаних з ними пакунків, які їх мають.
.PP
/var/lib/urpmi/compss
.br
Простий текстовий файл з описами для кожної Групи, із списком пакунків
в цій групі.

.SH "ДИВ. ТАКОЖ"
urpmi(8),
urpmq(8),
urpmi.addmedia(8),
urpmi.update(8),
urpmi.removemedia(8),
autoirpm(8),
autoirpm-icons(8),
.SH АВТОРИ
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com>
.br
Francois Pons, Mandrakesoft 
.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
