.TH urpmi 8 "05 Jul 2001" "Mandrakesoft" "Mandrakelinux"
.IX urpmi
.SH НАЗВА
urpmi \- обгортка для rpm, яка робить установку пакунків простішою для користувача
.SH ВИКОРИСТАННЯ
.B urpmi [\fIопції\fP] [\fIназви_пакунків\fP | \fIфайли_rpm...\fP]
.SH ОПИС
urpmi дозволяє провадити установку пакунків rpm користувачеві, який не
має адміністративних привілеїв. Насправді, він тільки дозволяє
установку добре відомих rpm. Якщо вам потрібно встановлювати локальні
rpm, ви все-таки повинні мати пароль root.

Ви можете порівнювати  rpm і urpmi  з insmod і  modprobe чи dpkg і apt-get
.PP
Всі користувачі, які належать до групи  urpmi можуть встановлювати пакунки.
.br
Просто запустіть на виконання  urpmi і додайте назви пакунків. Після
цього urpmi:
.br
\- Запропонує інші назви пакунків, якщо такі існують і закінчить роботу.
.br
\- Якщо знайдено тільки один відповідний пакунок, перевірить
залежності і чи пакунки, від яких залежить даний, вже встановлено чи ні.
.br
\- Якщо ні, запропонує встановити залежності і потім встановить всі
необхідні залежності і пакунок.
.PP
Зауважте, що  urpmi може встановлювати пакунки з різних носіїв (ftp,
http, локальні і змонтовані через nfs диски, змінні носії, такі як
компакт-диски, тощо) і також може встановлювати залежності з носіїв,
відмінних від тих, на яких знайдено сам пакунок.
Якщо потрібно urpmi попросить вас встановити потрібний носій.
.PP
Щоб додати новий носій до списку виконайте програму urpmi.addmedia.
.br
Щоб забрати носій з списку скористуйтесь програмою urpmi.removemedia.
.br
Для поновлення списку пакунків, які можуть бути встановленими
(наприклад, коли змінились архіви ftp) скористайтесь програмою urpmi.update.
.br
Щоб автоматично встановити пакунок, який відповідає програмі, що ви
намагались запустити, скористайтесь програмою autoirpm.
.br
Щоб встановити всі можливі пункти меню для всіх відомих пакунків
скористайтесь програмою utoirpm-icons.
.SH ПАРАМЕТРИ
.IP "\fB\--help\fP"
друкує підказку і закінчує роботу.
.IP "\fB\--update\fP"
користуватись тільки носіями для поновлення. Це означає, що
\fBurpmi\fP буде шукати і вирішувати залежності, тільки на тих носіях,
які позначені як носії для поновлення.
.IP "\fB\--auto\fP"
встановлює всі потрібні поновлення без зайвих запитань.
.IP "\fB\--auto-select\fP"
автоматично вибирає всі пакунки, які повинні бути поновленими
відповідно до вже встановлених і пакунків перечислених в
зареєстрованих носіях.
.IP "\fB\--force\fP"
вважається yes при відповідях на всі запитання.
.IP "\fB\--X\fP"
користуватись графічним інтерфейсом ( X Window).
.IP "\fB\--best-output\fP"
намагатися користуватись графічним інтерфейсом або якщо це неможливо
стандартним текстовим інтерфейсом (використовуючи rpm).
.IP "\fB\-a\fP"
якщо є кілька пакунків з назвою, що підходить до заданого шаблону,
взяти їх усі
.IP "\fB\-m\fP"
вибирати найменший набір потрібних пакунків (неявно встановлена
опція). Це \-\- повільний відносно алґоритм який намагається зменшити
кількість пакунків для поновлення до мінімально необхідного набору.
.IP "\fB\-M\fP"
вибирати найбільший набір потрібних пакунків. Найшвидший алґоритм,
який намагається поновити всі необхідні пакети, якщо вони можуть бути
поновлені.
.IP "\fB\-c\fP"
якщо використовується максимальний набір пакунків, вважати, що
перелічені пакунки можуть мати невірні чи застарілі залежності. Це
приводить до того, що більша кількість пакунків буде поновлена, і що
це можливо приведе до коригування залежностей в базі даних rpm.
.IP "\fB\-p\fP"
дозволяє пошук в списку пакунків типу "забезпечує" (provides).
.IP "\fB\-q\fP"
мовчазний режим установки rpm, коли не друкується інформація про стан
поновлення. 
.IP "\fB\-v\fP"
вмикає режим розширених повідомлень.
.SH ФАЙЛИ
/usr/bin/urpmi
.br
Двійковий файл \fBurpmi\fP (скрипт на мові Perl )
.PP
/var/lib/urpmi/list.*
.br
Список всіх пакунків відомих urpmi і їхні розташування.
Для кожного носія існує окремий список. 
.PP
/var/lib/urpmi/hdlist.*
.br
Інформація про всі відомі пакунки, це \-\- звідна інформація
заголовків пакунків rpm.  Для кожного носія існує окремий список. 
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Збірна інформація про всі відомі пакунки, побудовані з файлів hdlist,
які можуть використовуватись алгоритмом найменшого набору. Якщо ці
файли не існують, скористайтесь командою  \fBurpmi.update -a\fP щоб
їх створити. Це \-\- необов'язкові файли.
.PP
/etc/urpmi/urpmi.cfg
.br
Описи носіїв, застарілий формат від старіших urpmi допускається тут.
.PP
/etc/urpmi/skip.list
.br
Містить назви пакунків, які не повинні поновлюватись автоматично.
.PP
/var/lib/urpmi/depslist.ordered
.br
Простий текстовий файл з описами всіх залежностей всіх відомих пакунків.
.PP
/var/lib/urpmi/provides
.br
Простий текстовий файл з описами всіх пакунків, властивостей наданих
ними ("provides") і зв'язаних з ними пакунків, які їх мають.
.PP
/var/lib/urpmi/compss
.br
Простий текстовий файл з описами для кожної Групи, із списком пакунків
в цій групі.

.SH "ДИВ. ТАКОЖ"
urpmi.addmedia(8),
urpmi.update(8),
urpmi.removemedia(8),
autoirpm(8),
urpmf(8),
urpmq(8),
.SH АВТОРИ
Pascal Rigaux, Mandrakesoft <pixel@mandrakesoft.com>
.br
Francois Pons, Mandrakesoft 
.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
