.TH urpmq 8 "05 Jul 2001" "Mandrakesoft" "Mandrakelinux"
.IX urpmq
.SH НАЗВА
urpmq \- інструмент для запитів до бази даних urpmi.
.SH ВИКОРИСТАННЯ
.B urpmq [\fIопції\fP] [\fIназви_пакунків\fP | \fIфайли_rpm...\fP]
.SH ОПИС
urpmq дозволяє отримувати відповіді на запити з бази даних  urpmi. Ця
програма для вас, якщо вам потрібно перелічити пакунки на
різноманітних носіях, що працюють з urpmi, перелічити залежності
пакунків чи пакунки, які будуть встановлені при запуску urpmi.
.PP
Вихідний формат urpmq в залежності від наданих йому командних опцій
такий: 
.IP
[група/]назва_пакунку[-версія][-випуск]
.SH ПАРАМЕТРИ
.IP "\fB\--help\fP"
друкує підказку і закінчує роботу.
.IP "\fB\--update\fP"
користуватись тільки носіями для поновлення. Це означає, що
\fBurpmq\fP буде шукати і вирішувати залежності, тільки на тих носіях,
які позначені як носії для поновлення.
.IP "\fB\--auto-select\fP"
автоматично вибирає всі пакунки, які повинні бути поновленими
відповідно до вже встановлених і пакунків перечислених в
зареєстрованих носіях.
.IP "\fB\--headers\fP"
надрукувати заголовок вибраного пакунку на стандартний вивід.
.IP "\fB\--sources\fP"
надрукувати вихідний url (чи файл) для всіх вибраних пакунків.
.IP "\fB\--force\fP"
не звертати уваги на помилки про запит інформації про неіснуючі
пакунки. 
.IP "\fB\-v\fP"
режим багатослівних повідомлень.
.IP "\fB\-d\fP"
вибрати залежності (максимальний набір).
.IP "\fB\-u\fP"
відмінити вибір пакунків якщо вже встановлена краща версія, ця опція
може використовуватись разом з  \fB-d\fP для моделювання режиму \fB-M\fP \fBurpmi\fP.
.IP "\fB\-m\fP"
вибирати найменший набір потрібних пакунків (неявно встановлена
опція). Це \-\- повільний відносно алґоритм який намагається зменшити
кількість пакунків для поновлення до мінімально необхідного набору.
.IP "\fB\-M\fP"
заборонити алґоритм найменшого набору пакунків, таким чином, що обидва
\fB-d\fP і \fB-u\fP подібні до режиму \fB-M\fP \fBurpmi\fP.
.IP "\fB\-c\fP"
якщо використовується максимальний набір пакунків, вважати, що
перелічені пакунки можуть мати невірні чи застарілі залежності. Це
приводить до того, що більша кількість пакунків буде поновлена, і що
це можливо приведе до коригування залежностей в базі даних rpm.
.IP "\fB\-p\fP"
дозволяє пошук в списку пакунків типу "забезпечує" (provides).
.IP "\fB\-g\fP"
друкує групу кожного вибраного пакунку.
.IP "\fB\-r\fP"
друкує версію і випуск кожного вибраного пакунку.
.IP "\fB\-d\fP"
друкує оточення із пакунків необхідних для запрошеного пакунка.
.SH ФАЙЛИ
/usr/bin/urpmq
.br
Двійковий файл \fBurpmq\fP (скрипт на мові Perl )
.PP
/var/lib/urpmi/list.*
.br
Список всіх пакунків відомих urpmi і їхні розташування.
Для кожного носія існує окремий список. 
.PP
/var/lib/urpmi/list.*
.br
Список всіх пакунків відомих urpmi і їхні розташування.
Для кожного носія існує окремий список. 
.PP
/var/lib/urpmi/hdlist.*
.br
Інформація про всі відомі пакунки, це \-\- звідна інформація
заголовків пакунків rpm.  Для кожного носія існує окремий список. 
.PP
/var/lib/urpmi/synthesis.hdlist.*
.br
Збірна інформація про всі відомі пакунки, побудовані з файлів hdlist,
які можуть використовуватись алгоритмом найменшого набору. Якщо ці
файли не існують, скористайтесь командою  \fBurpmi.update -a\fP щоб
їх створити. Це \-\- необов'язкові файли.
.PP
/etc/urpmi/urpmi.cfg
.br
Описи носіїв, застарілий формат від старіших urpmi допускається тут.
.PP
/etc/urpmi/skip.list
.br
Містить назви пакунків, які не повинні поновлюватись автоматично.
.PP
/var/lib/urpmi/depslist.ordered
.br
Простий текстовий файл з описами всіх залежностей всіх відомих пакунків.
.PP
/var/lib/urpmi/provides
.br
Простий текстовий файл з описами всіх пакунків, властивостей наданих
ними ("provides") і зв'язаних з ними пакунків, які їх мають.
.PP
/var/lib/urpmi/compss
.br
Простий текстовий файл з описами для кожної Групи, із списком пакунків
в цій групі.
.SH "ДИВ. ТАКОЖ"
urpmi(8),
urpmi.addmedia(8),
urpmi.update(8),
urpmi.removemedia(8),
autoirpm(8),
urpmf(8),
.SH АВТОРИ
Francois Pons, Mandrakesoft
.br

.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
